; generated by Component: ARM Compiler 5.05 update 1 (build 106) Tool: ArmCC [4d0efa]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\stm32f0xx_hal_rtc.o --depend=.\objects\stm32f0xx_hal_rtc.d --cpu=Cortex-M0 --apcs=interwork -O0 --diag_suppress=9931 -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE\Device\STM32F071VBTx -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0 -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\CMSIS\Device\ST\STM32F0xx\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc\Legacy -D__UVISION_VERSION=514 -D_RTE_ -DSTM32F071xB --omf_browse=.\objects\stm32f0xx_hal_rtc.crf C:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Src\stm32f0xx_hal_rtc.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.HAL_RTC_AlarmAEventCallback||, CODE, READONLY, ALIGN=1

HAL_RTC_AlarmAEventCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RTC_AlarmIRQHandler||, CODE, READONLY, ALIGN=2

HAL_RTC_AlarmIRQHandler PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#12
        ANDS     r0,r0,r1
        LSRS     r0,r0,#12
        CMP      r0,#0
        BEQ      |L2.56|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        ASRS     r1,r1,#4
        ANDS     r0,r0,r1
        LSRS     r0,r0,#8
        CMP      r0,#0
        BEQ      |L2.56|
        MOV      r0,r4
        BL       HAL_RTC_AlarmAEventCallback
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        ANDS     r0,r0,r1
        LDR      r1,|L2.72|
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
|L2.56|
        MOVS     r0,#1
        LSLS     r0,r0,#17
        LDR      r1,|L2.76|
        STR      r0,[r1,#0x14]
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L2.72|
        DCD      0xfffffe7f
|L2.76|
        DCD      0x40010400

        AREA ||i.HAL_RTC_DeInit||, CODE, READONLY, ALIGN=2

HAL_RTC_DeInit PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOV      r0,r4
        BL       RTC_EnterInitMode
        CMP      r0,#0
        BEQ      |L3.54|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#1
|L3.52|
        POP      {r4-r6,pc}
|L3.54|
        MOVS     r0,#0
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,|L3.248|
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        LSLS     r0,r0,#29
        LSRS     r0,r0,#29
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        BL       HAL_GetTick
        MOV      r5,r0
        B        |L3.116|
|L3.86|
        BL       HAL_GetTick
        SUBS     r0,r0,r5
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L3.116|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#3
        STRB     r0,[r4,#0x1d]
        B        |L3.52|
|L3.116|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#4
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L3.86|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r0,#0
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,|L3.252|
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x14]
        LDR      r0,|L3.256|
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x10]
        MOVS     r0,#0
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x2c]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x3c]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x44]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x40]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L3.216|
        MOV      r0,r4
        BL       HAL_RTC_WaitForSynchro
        CMP      r0,#0
        BEQ      |L3.216|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#1
        B        |L3.52|
|L3.216|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOV      r0,r4
        BL       HAL_RTC_MspDeInit
        MOVS     r0,#0
        STRB     r0,[r4,#0x1d]
        NOP      
        STRB     r0,[r4,#0x1c]
        NOP      
        NOP      
        B        |L3.52|
        ENDP

        DCW      0x0000
|L3.248|
        DCD      0x00002101
|L3.252|
        DCD      0x0000ffff
|L3.256|
        DCD      0x007f00ff

        AREA ||i.HAL_RTC_DeactivateAlarm||, CODE, READONLY, ALIGN=1

HAL_RTC_DeactivateAlarm PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOVS     r5,#0
        NOP      
        LDRB     r0,[r4,#0x1c]
        CMP      r0,#1
        BNE      |L4.20|
        MOVS     r0,#2
|L4.18|
        POP      {r4-r6,pc}
|L4.20|
        MOVS     r0,#1
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#12
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        BL       HAL_GetTick
        MOV      r5,r0
        B        |L4.122|
|L4.82|
        BL       HAL_GetTick
        SUBS     r0,r0,r5
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L4.122|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#3
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#3
        B        |L4.18|
|L4.122|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L4.82|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        NOP      
        B        |L4.18|
        ENDP


        AREA ||i.HAL_RTC_GetAlarm||, CODE, READONLY, ALIGN=2

HAL_RTC_GetAlarm PROC
        PUSH     {r3-r7,lr}
        MOV      r6,r0
        MOV      r4,r1
        MOV      r7,r3
        MOVS     r5,#0
        MOVS     r0,#0
        STR      r0,[sp,#0]
        MOVS     r0,#0xff
        ADDS     r0,#1
        STR      r0,[r4,#0x24]
        LDR      r0,[r6,#0]
        LDR      r5,[r0,#0x1c]
        LDR      r0,[r6,#0]
        LDR      r0,[r0,#0x44]
        LSLS     r0,r0,#17
        LSRS     r0,r0,#17
        STR      r0,[sp,#0]
        MOVS     r0,#0x3f
        LSLS     r0,r0,#16
        ANDS     r0,r0,r5
        LSRS     r0,r0,#16
        STRB     r0,[r4,#0]
        MOVS     r0,#0x7f
        LSLS     r0,r0,#8
        ANDS     r0,r0,r5
        LSRS     r0,r0,#8
        STRB     r0,[r4,#1]
        LSLS     r0,r5,#25
        LSRS     r0,r0,#25
        STRB     r0,[r4,#2]
        MOVS     r0,#1
        LSLS     r0,r0,#22
        ANDS     r0,r0,r5
        LSRS     r0,r0,#16
        STRB     r0,[r4,#3]
        LDR      r0,[sp,#0]
        STR      r0,[r4,#4]
        MOVS     r0,#0x3f
        LSLS     r0,r0,#24
        ANDS     r0,r0,r5
        LSRS     r1,r0,#24
        MOVS     r0,#0x20
        STRB     r1,[r0,r4]
        LSLS     r0,r0,#25
        ANDS     r0,r0,r5
        STR      r0,[r4,#0x1c]
        LDR      r0,|L5.144|
        ANDS     r0,r0,r5
        STR      r0,[r4,#0x14]
        CMP      r7,#0
        BNE      |L5.138|
        LDRB     r0,[r4,#0]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#0]
        LDRB     r0,[r4,#1]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#1]
        LDRB     r0,[r4,#2]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#2]
        MOVS     r1,#0x20
        LDRB     r0,[r1,r4]
        BL       RTC_Bcd2ToByte
        MOVS     r1,#0x20
        STRB     r0,[r1,r4]
|L5.138|
        MOVS     r0,#0
        POP      {r3-r7,pc}
        ENDP

        DCW      0x0000
|L5.144|
        DCD      0x80808080

        AREA ||i.HAL_RTC_GetDate||, CODE, READONLY, ALIGN=2

HAL_RTC_GetDate PROC
        PUSH     {r4-r7,lr}
        MOV      r6,r0
        MOV      r4,r1
        MOV      r7,r2
        MOVS     r5,#0
        LDR      r0,[r6,#0]
        LDR      r0,[r0,#4]
        LDR      r1,|L6.88|
        ANDS     r0,r0,r1
        MOV      r5,r0
        MOVS     r0,#0xff
        LSLS     r0,r0,#16
        ANDS     r0,r0,r5
        LSRS     r0,r0,#16
        STRB     r0,[r4,#3]
        MOVS     r0,#0x1f
        LSLS     r0,r0,#8
        ANDS     r0,r0,r5
        LSRS     r0,r0,#8
        STRB     r0,[r4,#1]
        LSLS     r0,r5,#26
        LSRS     r0,r0,#26
        STRB     r0,[r4,#2]
        MOVS     r0,#7
        LSLS     r0,r0,#13
        ANDS     r0,r0,r5
        LSRS     r0,r0,#13
        STRB     r0,[r4,#0]
        CMP      r7,#0
        BNE      |L6.84|
        LDRB     r0,[r4,#3]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#3]
        LDRB     r0,[r4,#1]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#1]
        LDRB     r0,[r4,#2]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#2]
|L6.84|
        MOVS     r0,#0
        POP      {r4-r7,pc}
        ENDP

|L6.88|
        DCD      0x00ffff3f

        AREA ||i.HAL_RTC_GetState||, CODE, READONLY, ALIGN=1

HAL_RTC_GetState PROC
        MOV      r1,r0
        LDRB     r0,[r1,#0x1d]
        BX       lr
        ENDP


        AREA ||i.HAL_RTC_GetTime||, CODE, READONLY, ALIGN=2

HAL_RTC_GetTime PROC
        PUSH     {r4-r7,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOV      r7,r2
        MOVS     r6,#0
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0x28]
        STR      r0,[r4,#4]
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0x10]
        LSLS     r0,r0,#17
        LSRS     r0,r0,#17
        STR      r0,[r4,#8]
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        LDR      r1,|L8.104|
        ANDS     r0,r0,r1
        MOV      r6,r0
        MOVS     r0,#0x3f
        LSLS     r0,r0,#16
        ANDS     r0,r0,r6
        LSRS     r0,r0,#16
        STRB     r0,[r4,#0]
        MOVS     r0,#0x7f
        LSLS     r0,r0,#8
        ANDS     r0,r0,r6
        LSRS     r0,r0,#8
        STRB     r0,[r4,#1]
        LSLS     r0,r6,#25
        LSRS     r0,r0,#25
        STRB     r0,[r4,#2]
        MOVS     r0,#1
        LSLS     r0,r0,#22
        ANDS     r0,r0,r6
        LSRS     r0,r0,#16
        STRB     r0,[r4,#3]
        CMP      r7,#0
        BNE      |L8.100|
        LDRB     r0,[r4,#0]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#0]
        LDRB     r0,[r4,#1]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#1]
        LDRB     r0,[r4,#2]
        BL       RTC_Bcd2ToByte
        STRB     r0,[r4,#2]
|L8.100|
        MOVS     r0,#0
        POP      {r4-r7,pc}
        ENDP

|L8.104|
        DCD      0x007f7f7f

        AREA ||i.HAL_RTC_Init||, CODE, READONLY, ALIGN=2

HAL_RTC_Init PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L9.12|
        MOVS     r0,#1
|L9.10|
        POP      {r4,pc}
|L9.12|
        LDRB     r0,[r4,#0x1d]
        CMP      r0,#0
        BNE      |L9.26|
        STRB     r0,[r4,#0x1c]
        MOV      r0,r4
        BL       HAL_RTC_MspInit
|L9.26|
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOV      r0,r4
        BL       RTC_EnterInitMode
        CMP      r0,#0
        BEQ      |L9.74|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#1
        B        |L9.10|
|L9.74|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        LDR      r1,|L9.224|
        ANDS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r1,[r4,#0x10]
        LDR      r0,[r4,#4]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x14]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        LDR      r1,[r1,#8]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r1,[r4,#0]
        LDR      r0,[r4,#0xc]
        STR      r0,[r1,#0x10]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x10]
        LDRH     r1,[r4,#8]
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x10]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L9.178|
        MOV      r0,r4
        BL       HAL_RTC_WaitForSynchro
        CMP      r0,#0
        BEQ      |L9.178|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#1
        B        |L9.10|
|L9.178|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x40]
        MOVS     r1,#1
        LSLS     r1,r1,#18
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x40]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x40]
        LDR      r1,[r4,#0x18]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x40]
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#0
        B        |L9.10|
        ENDP

        DCW      0x0000
|L9.224|
        DCD      0xff8fffbf

        AREA ||i.HAL_RTC_MspDeInit||, CODE, READONLY, ALIGN=1

HAL_RTC_MspDeInit PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RTC_MspInit||, CODE, READONLY, ALIGN=1

HAL_RTC_MspInit PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RTC_PollForAlarmAEvent||, CODE, READONLY, ALIGN=2

HAL_RTC_PollForAlarmAEvent PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        BL       HAL_GetTick
        MOV      r6,r0
        B        |L12.40|
|L12.14|
        ADDS     r0,r5,#1
        CMP      r0,#0
        BEQ      |L12.40|
        CMP      r5,#0
        BEQ      |L12.34|
        BL       HAL_GetTick
        SUBS     r0,r0,r6
        CMP      r0,r5
        BLS      |L12.40|
|L12.34|
        MOVS     r0,#3
        STRB     r0,[r4,#0x1d]
|L12.38|
        POP      {r4-r6,pc}
|L12.40|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ANDS     r0,r0,r1
        LSRS     r0,r0,#8
        CMP      r0,#0
        BEQ      |L12.14|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        ANDS     r0,r0,r1
        LDR      r1,|L12.80|
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        MOVS     r0,#0
        B        |L12.38|
        ENDP

|L12.80|
        DCD      0xfffffe7f

        AREA ||i.HAL_RTC_SetAlarm||, CODE, READONLY, ALIGN=1

HAL_RTC_SetAlarm PROC
        PUSH     {r1-r7,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOV      r6,r2
        MOVS     r7,#0
        MOVS     r0,#0
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        NOP      
        LDRB     r0,[r5,#0x1c]
        CMP      r0,#1
        BNE      |L13.28|
        MOVS     r0,#2
|L13.26|
        POP      {r1-r7,pc}
|L13.28|
        MOVS     r0,#1
        STRB     r0,[r5,#0x1c]
        NOP      
        MOVS     r0,#2
        STRB     r0,[r5,#0x1d]
        CMP      r6,#0
        BNE      |L13.128|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L13.56|
        B        |L13.62|
|L13.56|
        MOVS     r0,#0
        STRB     r0,[r4,#3]
        NOP      
|L13.62|
        LDR      r0,[r4,#0x1c]
        CMP      r0,#0
        BNE      |L13.70|
        B        |L13.72|
|L13.70|
        NOP      
|L13.72|
        LDRB     r0,[r4,#0]
        BL       RTC_ByteToBcd2
        LSLS     r3,r0,#16
        LDRB     r0,[r4,#1]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#8
        ORRS     r3,r3,r0
        LDRB     r0,[r4,#2]
        BL       RTC_ByteToBcd2
        ORRS     r3,r3,r0
        LDRB     r0,[r4,#3]
        LSLS     r0,r0,#16
        ORRS     r3,r3,r0
        MOVS     r1,#0x20
        LDRB     r0,[r1,r4]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#24
        ORRS     r3,r3,r0
        LDR      r0,[r4,#0x1c]
        ORRS     r3,r3,r0
        LDR      r0,[r4,#0x14]
        ORRS     r3,r3,r0
        STR      r3,[sp,#4]
        B        |L13.224|
|L13.128|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L13.150|
        LDRB     r0,[r4,#0]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        B        |L13.156|
|L13.150|
        MOVS     r0,#0
        STRB     r0,[r4,#3]
        NOP      
|L13.156|
        LDR      r0,[r4,#0x1c]
        CMP      r0,#0
        BNE      |L13.174|
        MOVS     r1,#0x20
        LDRB     r0,[r1,r4]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        B        |L13.186|
|L13.174|
        MOVS     r1,#0x20
        LDRB     r0,[r1,r4]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        NOP      
|L13.186|
        LDRB     r0,[r4,#0]
        LSLS     r0,r0,#16
        LDRB     r1,[r4,#1]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDRB     r1,[r4,#2]
        ORRS     r0,r0,r1
        LDRB     r1,[r4,#3]
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        MOVS     r1,#0x20
        LDRB     r1,[r1,r4]
        LSLS     r1,r1,#24
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x1c]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x14]
        ORRS     r0,r0,r1
        STR      r0,[sp,#4]
|L13.224|
        LDR      r1,[r4,#0x18]
        LDR      r0,[r4,#4]
        ORRS     r0,r0,r1
        STR      r0,[sp,#0]
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x24]
        NOP      
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        BICS     r0,r0,r1
        LDR      r1,[r5,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#12
        BICS     r0,r0,r1
        LDR      r1,[r5,#0]
        STR      r0,[r1,#8]
        BL       HAL_GetTick
        MOV      r7,r0
        B        |L13.324|
|L13.284|
        BL       HAL_GetTick
        SUBS     r0,r0,r7
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L13.324|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#3
        STRB     r0,[r5,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r5,#0x1c]
        NOP      
        MOVS     r0,#3
        B        |L13.26|
|L13.324|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0xc]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L13.284|
        LDR      r0,[sp,#4]
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[sp,#0]
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x44]
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ORRS     r0,r0,r1
        LDR      r1,[r5,#0]
        STR      r0,[r1,#8]
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r5,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r5,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r5,#0x1c]
        NOP      
        NOP      
        B        |L13.26|
        ENDP


        AREA ||i.HAL_RTC_SetAlarm_IT||, CODE, READONLY, ALIGN=2

HAL_RTC_SetAlarm_IT PROC
        PUSH     {r1-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOVS     r7,#0
        MOVS     r0,#0
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        NOP      
        LDRB     r0,[r4,#0x1c]
        CMP      r0,#1
        BNE      |L14.28|
        MOVS     r0,#2
|L14.26|
        POP      {r1-r7,pc}
|L14.28|
        MOVS     r0,#1
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        CMP      r6,#0
        BNE      |L14.128|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L14.56|
        B        |L14.62|
|L14.56|
        MOVS     r0,#0
        STRB     r0,[r5,#3]
        NOP      
|L14.62|
        LDR      r0,[r5,#0x1c]
        CMP      r0,#0
        BNE      |L14.70|
        B        |L14.72|
|L14.70|
        NOP      
|L14.72|
        LDRB     r0,[r5,#0]
        BL       RTC_ByteToBcd2
        LSLS     r3,r0,#16
        LDRB     r0,[r5,#1]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#8
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#2]
        BL       RTC_ByteToBcd2
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#3]
        LSLS     r0,r0,#16
        ORRS     r3,r3,r0
        MOVS     r1,#0x20
        LDRB     r0,[r1,r5]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#24
        ORRS     r3,r3,r0
        LDR      r0,[r5,#0x1c]
        ORRS     r3,r3,r0
        LDR      r0,[r5,#0x14]
        ORRS     r3,r3,r0
        STR      r3,[sp,#4]
        B        |L14.224|
|L14.128|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L14.150|
        LDRB     r0,[r5,#0]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        B        |L14.156|
|L14.150|
        MOVS     r0,#0
        STRB     r0,[r5,#3]
        NOP      
|L14.156|
        LDR      r0,[r5,#0x1c]
        CMP      r0,#0
        BNE      |L14.174|
        MOVS     r1,#0x20
        LDRB     r0,[r1,r5]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        B        |L14.186|
|L14.174|
        MOVS     r1,#0x20
        LDRB     r0,[r1,r5]
        BL       RTC_Bcd2ToByte
        STR      r0,[sp,#4]
        NOP      
|L14.186|
        LDRB     r0,[r5,#0]
        LSLS     r0,r0,#16
        LDRB     r1,[r5,#1]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#2]
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#3]
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        MOVS     r1,#0x20
        LDRB     r1,[r1,r5]
        LSLS     r1,r1,#24
        ORRS     r0,r0,r1
        LDR      r1,[r5,#0x1c]
        ORRS     r0,r0,r1
        LDR      r1,[r5,#0x14]
        ORRS     r0,r0,r1
        STR      r0,[sp,#4]
|L14.224|
        LDR      r1,[r5,#0x18]
        LDR      r0,[r5,#4]
        ORRS     r0,r0,r1
        STR      r0,[sp,#0]
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        ANDS     r0,r0,r1
        LDR      r1,|L14.432|
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        BL       HAL_GetTick
        MOV      r7,r0
        B        |L14.326|
|L14.286|
        BL       HAL_GetTick
        SUBS     r0,r0,r7
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L14.326|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#3
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#3
        B        |L14.26|
|L14.326|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L14.286|
        LDR      r0,[sp,#4]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[sp,#0]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x44]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#12
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,|L14.436|
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#17
        ORRS     r0,r0,r1
        LDR      r1,|L14.436|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#17
        ORRS     r0,r0,r1
        LDR      r1,|L14.436|
        STR      r0,[r1,#8]
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        NOP      
        B        |L14.26|
        ENDP

|L14.432|
        DCD      0xfffffe7f
|L14.436|
        DCD      0x40010400

        AREA ||i.HAL_RTC_SetDate||, CODE, READONLY, ALIGN=2

HAL_RTC_SetDate PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOVS     r7,#0
        NOP      
        LDRB     r0,[r4,#0x1c]
        CMP      r0,#1
        BNE      |L15.22|
        MOVS     r0,#2
|L15.20|
        POP      {r3-r7,pc}
|L15.22|
        MOVS     r0,#1
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        CMP      r6,#0
        BNE      |L15.56|
        LDRB     r0,[r5,#1]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        CMP      r0,#0x10
        BNE      |L15.56|
        LDRB     r0,[r5,#1]
        MOVS     r1,#0xef
        ANDS     r0,r0,r1
        ADDS     r0,r0,#0xa
        STRB     r0,[r5,#1]
|L15.56|
        CMP      r6,#0
        BNE      |L15.96|
        LDRB     r0,[r5,#3]
        BL       RTC_ByteToBcd2
        LSLS     r3,r0,#16
        LDRB     r0,[r5,#1]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#8
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#2]
        BL       RTC_ByteToBcd2
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#0]
        LSLS     r0,r0,#13
        ORRS     r3,r3,r0
        MOV      r7,r3
        B        |L15.134|
|L15.96|
        LDRB     r0,[r5,#1]
        BL       RTC_Bcd2ToByte
        MOV      r7,r0
        LDRB     r0,[r5,#2]
        BL       RTC_Bcd2ToByte
        MOV      r7,r0
        LDRB     r0,[r5,#3]
        LSLS     r0,r0,#16
        LDRB     r1,[r5,#1]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#2]
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#0]
        LSLS     r1,r1,#13
        ORRS     r0,r0,r1
        MOV      r7,r0
|L15.134|
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOV      r0,r4
        BL       RTC_EnterInitMode
        CMP      r0,#0
        BEQ      |L15.186|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#1
        B        |L15.20|
|L15.186|
        LDR      r0,|L15.280|
        ANDS     r0,r0,r7
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L15.254|
        MOV      r0,r4
        BL       HAL_RTC_WaitForSynchro
        CMP      r0,#0
        BEQ      |L15.254|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#1
        B        |L15.20|
|L15.254|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        NOP      
        B        |L15.20|
        ENDP

|L15.280|
        DCD      0x00ffff3f

        AREA ||i.HAL_RTC_SetTime||, CODE, READONLY, ALIGN=2

HAL_RTC_SetTime PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOVS     r7,#0
        NOP      
        LDRB     r0,[r4,#0x1c]
        CMP      r0,#1
        BNE      |L16.22|
        MOVS     r0,#2
|L16.20|
        POP      {r3-r7,pc}
|L16.22|
        MOVS     r0,#1
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#2
        STRB     r0,[r4,#0x1d]
        CMP      r6,#0
        BNE      |L16.92|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L16.50|
        B        |L16.56|
|L16.50|
        MOVS     r0,#0
        STRB     r0,[r5,#3]
        NOP      
|L16.56|
        LDRB     r0,[r5,#0]
        BL       RTC_ByteToBcd2
        LSLS     r3,r0,#16
        LDRB     r0,[r5,#1]
        BL       RTC_ByteToBcd2
        LSLS     r0,r0,#8
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#2]
        BL       RTC_ByteToBcd2
        ORRS     r3,r3,r0
        LDRB     r0,[r5,#3]
        LSLS     r0,r0,#16
        ORRS     r3,r3,r0
        MOV      r7,r3
        B        |L16.142|
|L16.92|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L16.114|
        LDRB     r0,[r5,#0]
        BL       RTC_Bcd2ToByte
        MOV      r7,r0
        B        |L16.120|
|L16.114|
        MOVS     r0,#0
        STRB     r0,[r5,#3]
        NOP      
|L16.120|
        LDRB     r0,[r5,#0]
        LSLS     r0,r0,#16
        LDRB     r1,[r5,#1]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#2]
        ORRS     r0,r0,r1
        LDRB     r1,[r5,#3]
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        MOV      r7,r0
|L16.142|
        NOP      
        MOVS     r0,#0xca
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        MOVS     r0,#0x53
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOV      r0,r4
        BL       RTC_EnterInitMode
        CMP      r0,#0
        BEQ      |L16.194|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#1
        B        |L16.20|
|L16.194|
        LDR      r0,|L16.320|
        ANDS     r0,r0,r7
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#18
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r1,[r5,#0x10]
        LDR      r0,[r5,#0xc]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        LDR      r1,[r1,#8]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x80
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L16.292|
        MOV      r0,r4
        BL       HAL_RTC_WaitForSynchro
        CMP      r0,#0
        BEQ      |L16.292|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#4
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        MOVS     r0,#1
        B        |L16.20|
|L16.292|
        NOP      
        MOVS     r0,#0xff
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x24]
        NOP      
        MOVS     r0,#1
        STRB     r0,[r4,#0x1d]
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x1c]
        NOP      
        NOP      
        B        |L16.20|
        ENDP

        DCW      0x0000
|L16.320|
        DCD      0x007f7f7f

        AREA ||i.HAL_RTC_WaitForSynchro||, CODE, READONLY, ALIGN=1

HAL_RTC_WaitForSynchro PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0xa0
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        BL       HAL_GetTick
        MOV      r5,r0
        B        |L17.44|
|L17.26|
        BL       HAL_GetTick
        SUBS     r0,r0,r5
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L17.44|
        MOVS     r0,#3
|L17.42|
        POP      {r4-r6,pc}
|L17.44|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L17.26|
        MOVS     r0,#0
        B        |L17.42|
        ENDP


        AREA ||i.RTC_Bcd2ToByte||, CODE, READONLY, ALIGN=1

RTC_Bcd2ToByte PROC
        MOV      r1,r0
        NOP      
        MOVS     r0,#0xf0
        ANDS     r0,r0,r1
        ASRS     r0,r0,#4
        MOVS     r3,#0xa
        MULS     r0,r3,r0
        MOV      r2,r0
        LSLS     r0,r1,#28
        LSRS     r0,r0,#28
        ADDS     r0,r0,r2
        UXTB     r0,r0
        BX       lr
        ENDP


        AREA ||i.RTC_ByteToBcd2||, CODE, READONLY, ALIGN=1

RTC_ByteToBcd2 PROC
        MOV      r1,r0
        MOVS     r2,#0
        B        |L19.14|
|L19.6|
        ADDS     r2,r2,#1
        MOV      r0,r1
        SUBS     r0,r0,#0xa
        UXTB     r1,r0
|L19.14|
        CMP      r1,#0xa
        BCS      |L19.6|
        LSLS     r0,r2,#28
        LSRS     r0,r0,#24
        ORRS     r0,r0,r1
        BX       lr
        ENDP


        AREA ||i.RTC_EnterInitMode||, CODE, READONLY, ALIGN=1

RTC_EnterInitMode PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L20.62|
        SUBS     r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        BL       HAL_GetTick
        MOV      r5,r0
        B        |L20.50|
|L20.32|
        BL       HAL_GetTick
        SUBS     r0,r0,r5
        MOVS     r1,#0x7d
        LSLS     r1,r1,#3
        CMP      r0,r1
        BLS      |L20.50|
        MOVS     r0,#3
|L20.48|
        POP      {r4-r6,pc}
|L20.50|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0xc]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L20.32|
|L20.62|
        MOVS     r0,#0
        B        |L20.48|
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "C:\\Keil_v5\\ARM\\PACK\\Keil\\STM32F0xx_DFP\\2.0.0\\Drivers\\STM32F0xx_HAL_Driver\\Src\\stm32f0xx_hal_rtc.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___19_stm32f0xx_hal_rtc_c_c7052556____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___19_stm32f0xx_hal_rtc_c_c7052556____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___19_stm32f0xx_hal_rtc_c_c7052556____REVSH|
#line 478
|__asm___19_stm32f0xx_hal_rtc_c_c7052556____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_RTC_AlarmAEventCallback [CODE,WEAK]
        EXPORT HAL_RTC_AlarmIRQHandler [CODE]
        EXPORT HAL_RTC_DeInit [CODE]
        EXPORT HAL_RTC_DeactivateAlarm [CODE]
        EXPORT HAL_RTC_GetAlarm [CODE]
        EXPORT HAL_RTC_GetDate [CODE]
        EXPORT HAL_RTC_GetState [CODE]
        EXPORT HAL_RTC_GetTime [CODE]
        EXPORT HAL_RTC_Init [CODE]
        EXPORT HAL_RTC_MspDeInit [CODE,WEAK]
        EXPORT HAL_RTC_MspInit [CODE,WEAK]
        EXPORT HAL_RTC_PollForAlarmAEvent [CODE]
        EXPORT HAL_RTC_SetAlarm [CODE]
        EXPORT HAL_RTC_SetAlarm_IT [CODE]
        EXPORT HAL_RTC_SetDate [CODE]
        EXPORT HAL_RTC_SetTime [CODE]
        EXPORT HAL_RTC_WaitForSynchro [CODE]
        EXPORT RTC_Bcd2ToByte [CODE]
        EXPORT RTC_ByteToBcd2 [CODE]
        EXPORT RTC_EnterInitMode [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT HAL_GetTick [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
