; generated by Component: ARM Compiler 5.05 update 1 (build 106) Tool: ArmCC [4d0efa]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\stm32f0xx_hal_rcc_ex.o --depend=.\objects\stm32f0xx_hal_rcc_ex.d --cpu=Cortex-M0 --apcs=interwork -O0 --diag_suppress=9931 -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE\Device\STM32F071VBTx -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0 -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\CMSIS\Device\ST\STM32F0xx\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc\Legacy -D__UVISION_VERSION=514 -D_RTE_ -DSTM32F071xB --omf_browse=.\objects\stm32f0xx_hal_rcc_ex.crf C:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Src\stm32f0xx_hal_rcc_ex.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.HAL_RCCEx_CRSConfig||, CODE, READONLY, ALIGN=2

HAL_RCCEx_CRSConfig PROC
        MOVS     r1,#0
        LDR      r2,|L1.88|
        LDR      r2,[r2,#0x10]
        MOVS     r3,#1
        LSLS     r3,r3,#27
        ORRS     r2,r2,r3
        LDR      r3,|L1.88|
        STR      r2,[r3,#0x10]
        MOV      r2,r3
        LDR      r2,[r2,#0x10]
        LSLS     r3,r3,#15
        BICS     r2,r2,r3
        LDR      r3,|L1.88|
        STR      r2,[r3,#0x10]
        LDR      r3,[r0,#4]
        LDR      r2,[r0,#0]
        ORRS     r2,r2,r3
        LDR      r3,[r0,#8]
        ORRS     r2,r2,r3
        MOV      r1,r2
        LDR      r2,[r0,#0xc]
        ORRS     r1,r1,r2
        LDRH     r2,[r0,#0x10]
        LSLS     r2,r2,#16
        ORRS     r1,r1,r2
        LDR      r2,|L1.92|
        STR      r1,[r2,#4]
        LDR      r2,[r2,#0]
        MOVS     r3,#0x3f
        LSLS     r3,r3,#8
        BICS     r2,r2,r3
        LDR      r3,[r0,#0x14]
        LSLS     r3,r3,#8
        ORRS     r2,r2,r3
        LDR      r3,|L1.92|
        STR      r2,[r3,#0]
        MOV      r2,r3
        LDR      r2,[r2,#0]
        MOVS     r3,#0x60
        ORRS     r2,r2,r3
        LDR      r3,|L1.92|
        STR      r2,[r3,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L1.88|
        DCD      0x40021000
|L1.92|
        DCD      0x40006c00

        AREA ||i.HAL_RCCEx_CRSGetSynchronizationInfo||, CODE, READONLY, ALIGN=2

HAL_RCCEx_CRSGetSynchronizationInfo PROC
        LDR      r1,|L2.44|
        LDR      r1,[r1,#4]
        UXTH     r1,r1
        STR      r1,[r0,#0]
        LDR      r1,|L2.44|
        LDR      r1,[r1,#0]
        MOVS     r2,#0x3f
        LSLS     r2,r2,#8
        ANDS     r1,r1,r2
        LSRS     r1,r1,#8
        STR      r1,[r0,#4]
        LDR      r1,|L2.44|
        LDR      r1,[r1,#8]
        LSRS     r1,r1,#16
        STR      r1,[r0,#8]
        LDR      r1,|L2.44|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#15
        ANDS     r1,r1,r2
        STR      r1,[r0,#0xc]
        BX       lr
        ENDP

|L2.44|
        DCD      0x40006c00

        AREA ||i.HAL_RCCEx_CRSSoftwareSynchronizationGenerate||, CODE, READONLY, ALIGN=2

HAL_RCCEx_CRSSoftwareSynchronizationGenerate PROC
        LDR      r0,|L3.16|
        LDR      r0,[r0,#0]
        MOVS     r1,#0x80
        ORRS     r0,r0,r1
        LDR      r1,|L3.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L3.16|
        DCD      0x40006c00

        AREA ||i.HAL_RCCEx_CRSWaitSynchronization||, CODE, READONLY, ALIGN=2

HAL_RCCEx_CRSWaitSynchronization PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r4,#0
        MOVS     r6,#0
        BL       HAL_GetTick
        MOV      r6,r0
        NOP      
|L4.16|
        ADDS     r0,r5,#1
        CMP      r0,#0
        BEQ      |L4.38|
        CMP      r5,#0
        BEQ      |L4.36|
        BL       HAL_GetTick
        SUBS     r0,r0,r6
        CMP      r0,r5
        BLS      |L4.38|
|L4.36|
        MOVS     r4,#1
|L4.38|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L4.64|
        MOVS     r0,#2
        ORRS     r4,r4,r0
        NOP      
        MOVS     r0,#1
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.64|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#2
        BNE      |L4.90|
        MOVS     r0,#4
        ORRS     r4,r4,r0
        NOP      
        MOVS     r0,#2
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.90|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#10
        ANDS     r0,r0,r1
        CMP      r0,r1
        BNE      |L4.118|
        MOVS     r0,#0x20
        ORRS     r4,r4,r0
        NOP      
        MOVS     r0,#4
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.118|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ANDS     r0,r0,r1
        CMP      r0,r1
        BNE      |L4.146|
        MOVS     r0,#8
        ORRS     r4,r4,r0
        NOP      
        MOVS     r0,#4
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.146|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#9
        ANDS     r0,r0,r1
        CMP      r0,r1
        BNE      |L4.174|
        MOVS     r0,#0x10
        ORRS     r4,r4,r0
        NOP      
        MOVS     r0,#4
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.174|
        LDR      r0,|L4.204|
        LDR      r0,[r0,#8]
        MOVS     r1,#8
        ANDS     r0,r0,r1
        CMP      r0,#8
        BNE      |L4.194|
        NOP      
        LDR      r1,|L4.204|
        STR      r0,[r1,#0xc]
        NOP      
|L4.194|
        CMP      r4,#0
        BEQ      |L4.16|
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L4.204|
        DCD      0x40006c00

        AREA ||i.HAL_RCCEx_CRS_ErrorCallback||, CODE, READONLY, ALIGN=1

HAL_RCCEx_CRS_ErrorCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RCCEx_CRS_ExpectedSyncCallback||, CODE, READONLY, ALIGN=1

HAL_RCCEx_CRS_ExpectedSyncCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RCCEx_CRS_IRQHandler||, CODE, READONLY, ALIGN=2

HAL_RCCEx_CRS_IRQHandler PROC
        PUSH     {r4-r6,lr}
        MOVS     r5,#0
        LDR      r0,|L7.168|
        LDR      r4,[r0,#8]
        LDR      r6,[r0,#0]
        LSLS     r0,r4,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L7.38|
        LSLS     r0,r6,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L7.38|
        MOVS     r0,#1
        LDR      r1,|L7.168|
        STR      r0,[r1,#0xc]
        BL       HAL_RCCEx_CRS_SyncOkCallback
        B        |L7.164|
|L7.38|
        MOVS     r0,#2
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.66|
        MOVS     r0,#2
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L7.66|
        MOVS     r0,#2
        LDR      r1,|L7.168|
        STR      r0,[r1,#0xc]
        BL       HAL_RCCEx_CRS_SyncWarnCallback
        B        |L7.164|
|L7.66|
        MOVS     r0,#8
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.94|
        MOVS     r0,#8
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L7.94|
        MOVS     r0,#8
        LDR      r1,|L7.168|
        STR      r0,[r1,#0xc]
        BL       HAL_RCCEx_CRS_ExpectedSyncCallback
        B        |L7.164|
|L7.94|
        MOVS     r0,#4
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.164|
        MOVS     r0,#4
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L7.164|
        MOVS     r0,#0xff
        ADDS     r0,#1
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.124|
        MOVS     r0,#8
        ORRS     r5,r5,r0
|L7.124|
        MOVS     r0,#1
        LSLS     r0,r0,#9
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.138|
        MOVS     r0,#0x10
        ORRS     r5,r5,r0
|L7.138|
        MOVS     r0,#1
        LSLS     r0,r0,#10
        ANDS     r0,r0,r4
        CMP      r0,#0
        BEQ      |L7.152|
        MOVS     r0,#0x20
        ORRS     r5,r5,r0
|L7.152|
        MOVS     r0,#4
        LDR      r1,|L7.168|
        STR      r0,[r1,#0xc]
        MOV      r0,r5
        BL       HAL_RCCEx_CRS_ErrorCallback
|L7.164|
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L7.168|
        DCD      0x40006c00

        AREA ||i.HAL_RCCEx_CRS_SyncOkCallback||, CODE, READONLY, ALIGN=1

HAL_RCCEx_CRS_SyncOkCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RCCEx_CRS_SyncWarnCallback||, CODE, READONLY, ALIGN=1

HAL_RCCEx_CRS_SyncWarnCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_RCCEx_GetPeriphCLKConfig||, CODE, READONLY, ALIGN=2

HAL_RCCEx_GetPeriphCLKConfig PROC
        LDR      r1,|L10.80|
        STR      r1,[r0,#0]
        LDR      r1,|L10.84|
        LDR      r1,[r1,#0x20]
        MOVS     r2,#3
        LSLS     r2,r2,#8
        ANDS     r1,r1,r2
        STR      r1,[r0,#4]
        LDR      r1,|L10.84|
        LDR      r1,[r1,#0x30]
        LSLS     r1,r1,#30
        LSRS     r1,r1,#30
        STR      r1,[r0,#8]
        LDR      r1,|L10.84|
        LDR      r1,[r1,#0x30]
        MOVS     r2,#0x10
        ANDS     r1,r1,r2
        STR      r1,[r0,#0x10]
        MOVS     r2,#2
        LDR      r1,[r0,#0]
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,|L10.84|
        LDR      r1,[r1,#0x30]
        MOVS     r2,#3
        LSLS     r2,r2,#16
        ANDS     r1,r1,r2
        STR      r1,[r0,#0xc]
        MOVS     r2,#1
        LSLS     r2,r2,#10
        LDR      r1,[r0,#0]
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,|L10.84|
        LDR      r1,[r1,#0x30]
        MOVS     r2,#0x40
        ANDS     r1,r1,r2
        STR      r1,[r0,#0x14]
        BX       lr
        ENDP

        DCW      0x0000
|L10.80|
        DCD      0x00010021
|L10.84|
        DCD      0x40021000

        AREA ||i.HAL_RCCEx_GetPeriphCLKFreq||, CODE, READONLY, ALIGN=2

HAL_RCCEx_GetPeriphCLKFreq PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r6,#0
        MOVS     r4,#0
        CMP      r5,#0x20
        BEQ      |L11.246|
        BGT      |L11.24|
        CMP      r5,#1
        BEQ      |L11.126|
        CMP      r5,#2
|L11.20|
        BNE      |L11.248|
        B        |L11.198|
|L11.24|
        MOVS     r0,#1
        LSLS     r0,r0,#10
        SUBS     r0,r5,r0
        BEQ      |L11.250|
        MOVS     r1,#0x3f
        LSLS     r1,r1,#10
        SUBS     r0,r0,r1
        BNE      |L11.20|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#3
        LSLS     r1,r1,#8
        ANDS     r0,r0,r1
        MOV      r4,r0
        MOVS     r0,#0xff
        ADDS     r0,#1
        CMP      r4,r0
        BNE      |L11.76|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.76|
        LSLS     r6,r1,#14
        B        |L11.124|
|L11.76|
        MOVS     r0,#1
        LSLS     r0,r0,#9
        CMP      r4,r0
        BNE      |L11.100|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x24]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.100|
        LDR      r6,|L11.396|
        B        |L11.124|
|L11.100|
        MOVS     r0,#3
        LSLS     r0,r0,#8
        CMP      r4,r0
        BNE      |L11.124|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#17
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.124|
        LDR      r6,|L11.400|
|L11.124|
        B        |L11.386|
|L11.126|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x30]
        LSLS     r4,r0,#30
        LSRS     r4,r4,#30
        CMP      r4,#0
        BNE      |L11.146|
        BL       HAL_RCC_GetPCLK1Freq
        MOV      r6,r0
        B        |L11.196|
|L11.146|
        CMP      r4,#3
        BNE      |L11.166|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.166|
        LDR      r6,|L11.404|
        B        |L11.196|
|L11.166|
        CMP      r4,#1
        BNE      |L11.178|
        BL       HAL_RCC_GetSysClockFreq
        MOV      r6,r0
        B        |L11.196|
|L11.178|
        CMP      r4,#2
        BNE      |L11.196|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.196|
        LSLS     r6,r1,#14
|L11.196|
        B        |L11.386|
|L11.198|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#3
        LSLS     r1,r1,#16
        ANDS     r0,r0,r1
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L11.222|
        BL       HAL_RCC_GetPCLK1Freq
        MOV      r6,r0
        B        |L11.290|
|L11.222|
        MOVS     r0,#3
        LSLS     r0,r0,#16
        CMP      r4,r0
        BNE      |L11.252|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.252|
        LDR      r6,|L11.404|
        B        |L11.290|
|L11.246|
        B        |L11.292|
|L11.248|
        B        |L11.384|
|L11.250|
        B        |L11.334|
|L11.252|
        MOVS     r0,#1
        LSLS     r0,r0,#16
        CMP      r4,r0
        BNE      |L11.268|
        BL       HAL_RCC_GetSysClockFreq
        MOV      r6,r0
        B        |L11.290|
|L11.268|
        MOVS     r0,#1
        LSLS     r0,r0,#17
        CMP      r4,r0
        BNE      |L11.290|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.290|
        LSLS     r6,r1,#14
|L11.290|
        B        |L11.386|
|L11.292|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L11.322|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.322|
        LDR      r6,|L11.404|
        B        |L11.332|
|L11.322|
        CMP      r4,#0x10
        BNE      |L11.332|
        BL       HAL_RCC_GetSysClockFreq
        MOV      r6,r0
|L11.332|
        B        |L11.386|
|L11.334|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L11.364|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.364|
        LDR      r6,|L11.404|
        B        |L11.382|
|L11.364|
        CMP      r4,#0x40
        BNE      |L11.382|
        LDR      r0,|L11.392|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L11.382|
        LSLS     r6,r1,#14
|L11.382|
        B        |L11.386|
|L11.384|
        NOP      
|L11.386|
        NOP      
        MOV      r0,r6
        POP      {r4-r6,pc}
        ENDP

|L11.392|
        DCD      0x40021000
|L11.396|
        DCD      0x00009c40
|L11.400|
        DCD      0x0003d090
|L11.404|
        DCD      0x007a1200

        AREA ||i.HAL_RCCEx_PeriphCLKConfig||, CODE, READONLY, ALIGN=2

HAL_RCCEx_PeriphCLKConfig PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOVS     r6,#0
        MOVS     r5,#0
        MOVS     r1,#1
        LSLS     r1,r1,#16
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,r1
        BNE      |L12.266|
        MOVS     r7,#0
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x1c]
        LSLS     r1,r1,#12
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L12.62|
        NOP      
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x1c]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        LSLS     r1,r1,#16
        ANDS     r0,r0,r1
        STR      r0,[sp,#0]
        NOP      
        NOP      
        MOVS     r7,#1
|L12.62|
        LDR      r0,|L12.384|
        LDR      r0,[r0,#0]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ANDS     r0,r0,r1
        CMP      r0,#0
        BNE      |L12.122|
        LDR      r0,|L12.384|
        LDR      r0,[r0,#0]
        ORRS     r0,r0,r1
        LDR      r1,|L12.384|
        STR      r0,[r1,#0]
        BL       HAL_GetTick
        MOV      r6,r0
        B        |L12.108|
|L12.94|
        BL       HAL_GetTick
        SUBS     r0,r0,r6
        CMP      r0,#0x64
        BLS      |L12.108|
        MOVS     r0,#3
|L12.106|
        POP      {r3-r7,pc}
|L12.108|
        LDR      r0,|L12.384|
        LDR      r0,[r0,#0]
        MOVS     r1,#0xff
        ADDS     r1,#1
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L12.94|
|L12.122|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#3
        LSLS     r1,r1,#8
        ANDS     r0,r0,r1
        MOV      r5,r0
        CMP      r5,#0
        BEQ      |L12.230|
        LDR      r0,[r4,#4]
        ANDS     r0,r0,r1
        CMP      r0,r5
        BEQ      |L12.230|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x20]
        BICS     r0,r0,r1
        MOV      r5,r0
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#1
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        MOVS     r1,#1
        LSLS     r1,r1,#16
        BICS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        STR      r5,[r0,#0x20]
        LSLS     r0,r5,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L12.230|
        BL       HAL_GetTick
        MOV      r6,r0
        B        |L12.218|
|L12.202|
        BL       HAL_GetTick
        SUBS     r0,r0,r6
        LDR      r1,|L12.388|
        CMP      r0,r1
        BLS      |L12.218|
        MOVS     r0,#3
        B        |L12.106|
|L12.218|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L12.202|
|L12.230|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x20]
        MOVS     r1,#3
        LSLS     r1,r1,#8
        BICS     r0,r0,r1
        LDR      r1,[r4,#4]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x20]
        CMP      r7,#1
        BNE      |L12.264|
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        LSLS     r1,r1,#16
        BICS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x1c]
|L12.264|
        NOP      
|L12.266|
        LDRB     r0,[r4,#0]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L12.292|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x30]
        LSRS     r0,r0,#2
        LSLS     r0,r0,#2
        LDR      r1,[r4,#8]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x30]
|L12.292|
        MOVS     r1,#2
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,#2
        BNE      |L12.320|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#3
        LSLS     r1,r1,#16
        BICS     r0,r0,r1
        LDR      r1,[r4,#0xc]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x30]
|L12.320|
        MOVS     r1,#0x20
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,#0x20
        BNE      |L12.346|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,[r4,#0x10]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x30]
|L12.346|
        MOVS     r1,#1
        LSLS     r1,r1,#10
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,r1
        BNE      |L12.374|
        LDR      r0,|L12.380|
        LDR      r0,[r0,#0x30]
        MOVS     r1,#0x40
        BICS     r0,r0,r1
        LDR      r1,[r4,#0x14]
        ORRS     r0,r0,r1
        LDR      r1,|L12.380|
        STR      r0,[r1,#0x30]
|L12.374|
        MOVS     r0,#0
        B        |L12.106|
        ENDP

        DCW      0x0000
|L12.380|
        DCD      0x40021000
|L12.384|
        DCD      0x40007000
|L12.388|
        DCD      0x00001388

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "C:\\Keil_v5\\ARM\\PACK\\Keil\\STM32F0xx_DFP\\2.0.0\\Drivers\\STM32F0xx_HAL_Driver\\Src\\stm32f0xx_hal_rcc_ex.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f0xx_hal_rcc_ex_c_bed13b44____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___22_stm32f0xx_hal_rcc_ex_c_bed13b44____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f0xx_hal_rcc_ex_c_bed13b44____REVSH|
#line 478
|__asm___22_stm32f0xx_hal_rcc_ex_c_bed13b44____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_RCCEx_CRSConfig [CODE]
        EXPORT HAL_RCCEx_CRSGetSynchronizationInfo [CODE]
        EXPORT HAL_RCCEx_CRSSoftwareSynchronizationGenerate [CODE]
        EXPORT HAL_RCCEx_CRSWaitSynchronization [CODE]
        EXPORT HAL_RCCEx_CRS_ErrorCallback [CODE,WEAK]
        EXPORT HAL_RCCEx_CRS_ExpectedSyncCallback [CODE,WEAK]
        EXPORT HAL_RCCEx_CRS_IRQHandler [CODE]
        EXPORT HAL_RCCEx_CRS_SyncOkCallback [CODE,WEAK]
        EXPORT HAL_RCCEx_CRS_SyncWarnCallback [CODE,WEAK]
        EXPORT HAL_RCCEx_GetPeriphCLKConfig [CODE]
        EXPORT HAL_RCCEx_GetPeriphCLKFreq [CODE]
        EXPORT HAL_RCCEx_PeriphCLKConfig [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT HAL_GetTick [CODE]
        IMPORT HAL_RCC_GetPCLK1Freq [CODE]
        IMPORT HAL_RCC_GetSysClockFreq [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
