; generated by Component: ARM Compiler 5.05 update 1 (build 106) Tool: ArmCC [4d0efa]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\stm32f0xx_hal_smbus.o --depend=.\objects\stm32f0xx_hal_smbus.d --cpu=Cortex-M0 --apcs=interwork -O0 --diag_suppress=9931 -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE\Device\STM32F071VBTx -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0 -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\CMSIS\Device\ST\STM32F0xx\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc\Legacy -D__UVISION_VERSION=514 -D_RTE_ -DSTM32F071xB --omf_browse=.\objects\stm32f0xx_hal_smbus.crf C:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Src\stm32f0xx_hal_smbus.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.HAL_SMBUS_AddrCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_AddrCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_ConfigAnalogFilter||, CODE, READONLY, ALIGN=1

HAL_SMBUS_ConfigAnalogFilter PROC
        MOV      r2,r0
        LDR      r0,[r2,#0x48]
        CMP      r0,#1
        BNE      |L2.98|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r2]
        CMP      r0,#1
        BNE      |L2.22|
        MOVS     r0,#2
|L2.20|
        BX       lr
|L2.22|
        MOVS     r3,#1
        MOVS     r0,#0x44
        STRB     r3,[r0,r2]
        NOP      
        MOVS     r0,#2
        STR      r0,[r2,#0x48]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        BICS     r0,r0,r3
        LDR      r3,[r2,#0]
        STR      r0,[r3,#0]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r3,#1
        LSLS     r3,r3,#12
        BICS     r0,r0,r3
        LDR      r3,[r2,#0]
        STR      r0,[r3,#0]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        ORRS     r0,r0,r1
        LDR      r3,[r2,#0]
        STR      r0,[r3,#0]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r3,#1
        ORRS     r0,r0,r3
        LDR      r3,[r2,#0]
        STR      r0,[r3,#0]
        MOVS     r0,#1
        STR      r0,[r2,#0x48]
        NOP      
        MOVS     r3,#0
        MOVS     r0,#0x44
        STRB     r3,[r0,r2]
        NOP      
        MOVS     r0,#0
        B        |L2.20|
|L2.98|
        MOVS     r0,#2
        B        |L2.20|
        ENDP


        AREA ||i.HAL_SMBUS_ConfigDigitalFilter||, CODE, READONLY, ALIGN=1

HAL_SMBUS_ConfigDigitalFilter PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        MOV      r3,r1
        MOVS     r1,#0
        LDR      r0,[r2,#0x48]
        CMP      r0,#1
        BNE      |L3.102|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r2]
        CMP      r0,#1
        BNE      |L3.28|
        MOVS     r0,#2
|L3.26|
        POP      {r4,pc}
|L3.28|
        MOVS     r4,#1
        MOVS     r0,#0x44
        STRB     r4,[r0,r2]
        NOP      
        MOVS     r0,#2
        STR      r0,[r2,#0x48]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        BICS     r0,r0,r4
        LDR      r4,[r2,#0]
        STR      r0,[r4,#0]
        LDR      r0,[r2,#0]
        LDR      r1,[r0,#0]
        MOVS     r4,#0xf
        LSLS     r4,r4,#8
        MOV      r0,r1
        BICS     r0,r0,r4
        MOV      r1,r0
        LSLS     r0,r3,#8
        ORRS     r1,r1,r0
        LDR      r0,[r2,#0]
        STR      r1,[r0,#0]
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#1
        ORRS     r0,r0,r4
        LDR      r4,[r2,#0]
        STR      r0,[r4,#0]
        MOVS     r0,#1
        STR      r0,[r2,#0x48]
        NOP      
        MOVS     r4,#0
        MOVS     r0,#0x44
        STRB     r4,[r0,r2]
        NOP      
        MOVS     r0,#0
        B        |L3.26|
|L3.102|
        MOVS     r0,#2
        B        |L3.26|
        ENDP


        AREA ||i.HAL_SMBUS_DeInit||, CODE, READONLY, ALIGN=1

HAL_SMBUS_DeInit PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L4.12|
        MOVS     r0,#1
|L4.10|
        POP      {r4,pc}
|L4.12|
        MOVS     r0,#2
        STR      r0,[r4,#0x48]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        LSRS     r0,r0,#1
        LSLS     r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOV      r0,r4
        BL       HAL_SMBUS_MspDeInit
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        STR      r0,[r4,#0x40]
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0
        B        |L4.10|
        ENDP


        AREA ||i.HAL_SMBUS_DisableAlert_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_DisableAlert_IT PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#22
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r1,#0x80
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_SMBUS_DisableListen_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_DisableListen_IT PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,[r4,#0x48]
        CMP      r0,#8
        BNE      |L6.26|
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        MOVS     r1,#0x38
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        MOVS     r0,#0
|L6.24|
        POP      {r4,pc}
|L6.26|
        MOVS     r0,#2
        B        |L6.24|
        ENDP


        AREA ||i.HAL_SMBUS_ER_IRQHandler||, CODE, READONLY, ALIGN=1

HAL_SMBUS_ER_IRQHandler PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOV      r0,r4
        BL       SMBUS_ITErrorHandler
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_SMBUS_EV_IRQHandler||, CODE, READONLY, ALIGN=1

HAL_SMBUS_EV_IRQHandler PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r4,#0
        LDR      r0,[r5,#0]
        LDR      r4,[r0,#0x18]
        MOVS     r0,#2
        ANDS     r0,r0,r4
        LSRS     r0,r0,#1
        CMP      r0,#0
        BNE      |L8.60|
        MOVS     r0,#0x80
        ANDS     r0,r0,r4
        LSRS     r0,r0,#7
        CMP      r0,#0
        BNE      |L8.60|
        MOVS     r0,#0x40
        ANDS     r0,r0,r4
        LSRS     r0,r0,#6
        CMP      r0,#0
        BNE      |L8.60|
        MOVS     r0,#0x20
        ANDS     r0,r0,r4
        LSRS     r0,r0,#5
        CMP      r0,#0
        BNE      |L8.60|
        MOVS     r0,#0x10
        ANDS     r0,r0,r4
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L8.116|
|L8.60|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#0x72
        ANDS     r0,r0,r1
        CMP      r0,#0x72
        BNE      |L8.76|
        MOVS     r0,#1
        B        |L8.78|
|L8.76|
        MOVS     r0,#0
|L8.78|
        CMP      r0,#0
        BEQ      |L8.116|
        LDR      r0,[r5,#0x48]
        MOVS     r1,#0x32
        ANDS     r0,r0,r1
        CMP      r0,#0x32
        BNE      |L8.100|
        MOV      r0,r5
        BL       SMBUS_Slave_ISR
        B        |L8.116|
|L8.100|
        LDR      r0,[r5,#0x48]
        MOVS     r1,#0x12
        ANDS     r0,r0,r1
        CMP      r0,#0x12
        BNE      |L8.116|
        MOV      r0,r5
        BL       SMBUS_Master_ISR
|L8.116|
        MOVS     r0,#4
        ANDS     r0,r0,r4
        LSRS     r0,r0,#2
        CMP      r0,#0
        BNE      |L8.166|
        MOVS     r0,#0x80
        ANDS     r0,r0,r4
        LSRS     r0,r0,#7
        CMP      r0,#0
        BNE      |L8.166|
        MOVS     r0,#0x40
        ANDS     r0,r0,r4
        LSRS     r0,r0,#6
        CMP      r0,#0
        BNE      |L8.166|
        MOVS     r0,#0x20
        ANDS     r0,r0,r4
        LSRS     r0,r0,#5
        CMP      r0,#0
        BNE      |L8.166|
        MOVS     r0,#0x10
        ANDS     r0,r0,r4
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L8.222|
|L8.166|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#0x74
        ANDS     r0,r0,r1
        CMP      r0,#0x74
        BNE      |L8.182|
        MOVS     r0,#1
        B        |L8.184|
|L8.182|
        MOVS     r0,#0
|L8.184|
        CMP      r0,#0
        BEQ      |L8.222|
        LDR      r0,[r5,#0x48]
        MOVS     r1,#0x42
        ANDS     r0,r0,r1
        CMP      r0,#0x42
        BNE      |L8.206|
        MOV      r0,r5
        BL       SMBUS_Slave_ISR
        B        |L8.222|
|L8.206|
        LDR      r0,[r5,#0x48]
        MOVS     r1,#0x22
        ANDS     r0,r0,r1
        CMP      r0,#0x22
        BNE      |L8.222|
        MOV      r0,r5
        BL       SMBUS_Master_ISR
|L8.222|
        MOVS     r0,#8
        ANDS     r0,r0,r4
        LSRS     r0,r0,#3
        CMP      r0,#0
        BNE      |L8.252|
        MOVS     r0,#0x20
        ANDS     r0,r0,r4
        LSRS     r0,r0,#5
        CMP      r0,#0
        BNE      |L8.252|
        MOVS     r0,#0x10
        ANDS     r0,r0,r4
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L8.306|
|L8.252|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#8
        ANDS     r0,r0,r1
        LSRS     r0,r0,#3
        CMP      r0,#0
        BNE      |L8.294|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        LSRS     r0,r0,#5
        CMP      r0,#0
        BNE      |L8.294|
        LDR      r0,[r5,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L8.306|
|L8.294|
        LDR      r0,[r5,#0x48]
        CMP      r0,#8
        BNE      |L8.306|
        MOV      r0,r5
        BL       SMBUS_Slave_ISR
|L8.306|
        POP      {r4-r6,pc}
        ENDP


        AREA ||i.HAL_SMBUS_EnableAlert_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_EnableAlert_IT PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#22
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r0,#1
        LSLS     r0,r0,#13
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        MOVS     r1,#0x80
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_SMBUS_EnableListen_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_EnableListen_IT PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOVS     r0,#8
        STR      r0,[r4,#0x48]
        MOVS     r1,#0x38
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_SMBUS_ErrorCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_ErrorCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_GetError||, CODE, READONLY, ALIGN=1

HAL_SMBUS_GetError PROC
        MOV      r1,r0
        LDR      r0,[r1,#0x4c]
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_GetState||, CODE, READONLY, ALIGN=1

HAL_SMBUS_GetState PROC
        MOV      r1,r0
        LDR      r0,[r1,#0x48]
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_Init||, CODE, READONLY, ALIGN=2

HAL_SMBUS_Init PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L14.12|
        MOVS     r0,#1
|L14.10|
        POP      {r4,pc}
|L14.12|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0
        BNE      |L14.30|
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        MOV      r0,r4
        BL       HAL_SMBUS_MspInit
|L14.30|
        MOVS     r0,#2
        STR      r0,[r4,#0x48]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        LSRS     r0,r0,#1
        LSLS     r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r1,#0xf
        LSLS     r1,r1,#24
        LDR      r0,[r4,#4]
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x10]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x14]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x14]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x14]
        LSLS     r0,r0,#1
        LSRS     r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x14]
        LDR      r1,[r4,#0]
        LDR      r0,[r4,#0x30]
        STR      r0,[r1,#0x14]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#8]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        LDR      r0,[r4,#0xc]
        CMP      r0,#0
        BEQ      |L14.142|
        LDR      r0,[r4,#0x10]
        CMP      r0,#1
        BNE      |L14.130|
        MOVS     r1,#1
        LSLS     r1,r1,#15
        LDR      r0,[r4,#0xc]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
        B        |L14.142|
|L14.130|
        MOVS     r1,#0x21
        LSLS     r1,r1,#10
        LDR      r0,[r4,#0xc]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#8]
|L14.142|
        LDR      r0,[r4,#0x10]
        CMP      r0,#2
        BNE      |L14.154|
        LSLS     r0,r0,#10
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
|L14.154|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LDR      r1,|L14.268|
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        LDR      r1,[r4,#0x18]
        LDR      r0,[r4,#0x14]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x1c]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDR      r1,[r4,#0x24]
        LDR      r0,[r4,#0x20]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x28]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0x2c]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#8]
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#23
        LDR      r0,[r4,#0x28]
        CMP      r0,r1
        BNE      |L14.242|
        LDR      r0,[r4,#0x2c]
        CMP      r0,#0
        BEQ      |L14.228|
        ASRS     r1,r1,#2
        LDR      r0,[r4,#0x2c]
        CMP      r0,r1
        BNE      |L14.242|
|L14.228|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
|L14.242|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        MOVS     r0,#1
        STR      r0,[r4,#0x40]
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        B        |L14.10|
        ENDP

|L14.268|
        DCD      0x02008000

        AREA ||i.HAL_SMBUS_IsDeviceReady||, CODE, READONLY, ALIGN=1

HAL_SMBUS_IsDeviceReady PROC
        PUSH     {r1-r7,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r5,r3
        MOVS     r0,#0
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x48]
        CMP      r0,#1
        BNE      |L15.262|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        ANDS     r0,r0,r1
        LSRS     r0,r0,#15
        CMP      r0,#0
        BEQ      |L15.42|
        MOVS     r0,#2
|L15.40|
        POP      {r1-r7,pc}
|L15.42|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L15.56|
        MOVS     r0,#2
        B        |L15.40|
|L15.56|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#2
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        NOP      
|L15.74|
        LDR      r0,[r4,#0x10]
        CMP      r0,#1
        BNE      |L15.100|
        LSLS     r0,r6,#22
        LSRS     r0,r0,#22
        MOVS     r1,#1
        LSLS     r1,r1,#13
        ADDS     r0,r0,r1
        LSLS     r1,r1,#12
        ADDS     r0,r0,r1
        ASRS     r1,r1,#15
        BICS     r0,r0,r1
        B        |L15.118|
|L15.100|
        LSLS     r0,r6,#22
        LSRS     r0,r0,#22
        MOVS     r1,#1
        LSLS     r1,r1,#11
        ADDS     r0,r0,r1
        LSLS     r1,r1,#2
        ADDS     r0,r0,r1
        ASRS     r1,r1,#3
        BICS     r0,r0,r1
|L15.118|
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        BL       HAL_GetTick
        STR      r0,[sp,#4]
        B        |L15.170|
|L15.130|
        ADDS     r0,r5,#1
        CMP      r0,#0
        BEQ      |L15.170|
        CMP      r5,#0
        BEQ      |L15.152|
        BL       HAL_GetTick
        LDR      r1,[sp,#4]
        SUBS     r0,r0,r1
        CMP      r0,r5
        BLS      |L15.170|
|L15.152|
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#3
        B        |L15.40|
|L15.170|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        LSRS     r0,r0,#5
        CMP      r0,#0
        BNE      |L15.204|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        LSRS     r0,r0,#4
        CMP      r0,#0
        BNE      |L15.204|
        LDR      r0,[r4,#0x48]
        CMP      r0,#3
        BNE      |L15.130|
|L15.204|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        LSRS     r0,r0,#4
        CMP      r0,#0
        BNE      |L15.264|
        MOV      r3,r5
        MOVS     r2,#0
        MOVS     r1,#0x20
        MOV      r0,r4
        BL       SMBUS_WaitOnFlagUntilTimeout
        CMP      r0,#0
        BEQ      |L15.238|
        MOVS     r0,#3
        B        |L15.40|
|L15.238|
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0
        B        |L15.40|
|L15.262|
        B        |L15.372|
|L15.264|
        MOV      r3,r5
        MOVS     r2,#0
        MOVS     r1,#0x20
        MOV      r0,r4
        BL       SMBUS_WaitOnFlagUntilTimeout
        CMP      r0,#0
        BEQ      |L15.284|
        MOVS     r0,#3
        B        |L15.40|
|L15.284|
        MOVS     r0,#0x10
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[sp,#0]
        ADDS     r1,r0,#1
        STR      r1,[sp,#0]
        CMP      r0,r7
        BNE      |L15.346|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#14
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        MOV      r3,r5
        MOVS     r2,#0
        MOVS     r1,#0x20
        MOV      r0,r4
        BL       SMBUS_WaitOnFlagUntilTimeout
        CMP      r0,#0
        BEQ      |L15.340|
        MOVS     r0,#3
        B        |L15.40|
|L15.340|
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L15.346|
        LDR      r0,[sp,#0]
        CMP      r0,r7
        BCS      |L15.354|
        B        |L15.74|
|L15.354|
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#3
        B        |L15.40|
|L15.372|
        MOVS     r0,#2
        B        |L15.40|
        ENDP


        AREA ||i.HAL_SMBUS_ListenCpltCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_ListenCpltCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_MasterRxCpltCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_MasterRxCpltCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_MasterTxCpltCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_MasterTxCpltCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_Master_Abort_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_Master_Abort_IT PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        MOV      r5,r1
        LDR      r0,[r4,#0x48]
        CMP      r0,#1
        BNE      |L19.122|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L19.26|
        MOVS     r0,#2
|L19.24|
        POP      {r3-r5,pc}
|L19.26|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0x40]
        CMP      r0,#0x12
        BNE      |L19.44|
        STR      r0,[r4,#0x48]
        B        |L19.58|
|L19.44|
        LDR      r0,[r4,#0x40]
        CMP      r0,#0x22
        BNE      |L19.54|
        STR      r0,[r4,#0x48]
        B        |L19.58|
|L19.54|
        MOVS     r0,#1
        B        |L19.24|
|L19.58|
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        MOVS     r3,#1
        LSLS     r3,r3,#25
        MOVS     r2,#1
        MOV      r1,r5
        STR      r0,[sp,#0]
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x12
        BNE      |L19.104|
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        B        |L19.118|
|L19.104|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x22
        BNE      |L19.118|
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
|L19.118|
        MOVS     r0,#0
        B        |L19.24|
|L19.122|
        MOVS     r0,#2
        B        |L19.24|
        ENDP


        AREA ||i.HAL_SMBUS_Master_Receive_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_Master_Receive_IT PROC
        PUSH     {r0-r7,lr}
        SUB      sp,sp,#4
        MOV      r4,r0
        MOV      r6,r2
        MOV      r5,r3
        LDR      r7,[sp,#0x28]
        LDR      r0,[r4,#0x48]
        CMP      r0,#1
        BNE      |L20.246|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L20.34|
        MOVS     r0,#2
|L20.30|
        ADD      sp,sp,#0x14
        POP      {r4-r7,pc}
|L20.34|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0x22
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        STR      r6,[r4,#0x34]
        STRH     r5,[r4,#0x3a]
        STR      r7,[r4,#0x3c]
        LDR      r0,[r4,#0x34]
        CMP      r0,#0
        BNE      |L20.70|
        LDR      r0,[r4,#0x3c]
        LSLS     r1,r1,#25
        BICS     r0,r0,r1
        STR      r0,[r4,#0x3c]
|L20.70|
        CMP      r5,#0xff
        BLS      |L20.80|
        MOVS     r0,#0xff
        STRH     r0,[r4,#0x38]
        B        |L20.82|
|L20.80|
        STRH     r5,[r4,#0x38]
|L20.82|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0xff
        BNE      |L20.130|
        LDRH     r0,[r4,#0x38]
        LDRH     r1,[r4,#0x3a]
        CMP      r0,r1
        BGE      |L20.130|
        MOVS     r0,#9
        LSLS     r0,r0,#10
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
        B        |L20.222|
|L20.130|
        LDR      r0,[r4,#0x40]
        CMP      r0,#0x22
        BNE      |L20.196|
        LDR      r0,[r4,#0x3c]
        CMP      r0,#0xaa
        BEQ      |L20.168|
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#0x55
        LSLS     r1,r1,#17
        CMP      r0,r1
        BEQ      |L20.168|
        LDR      r0,[r4,#0x3c]
        ASRS     r1,r1,#8
        CMP      r0,r1
        BEQ      |L20.168|
        LDR      r0,[r4,#0x3c]
        LSLS     r1,r1,#16
        CMP      r0,r1
        BNE      |L20.172|
|L20.168|
        MOVS     r0,#1
        B        |L20.174|
|L20.172|
        MOVS     r0,#0
|L20.174|
        CMP      r0,#0
        BNE      |L20.196|
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
        B        |L20.222|
|L20.196|
        MOV      r0,r4
        BL       SMBUS_ConvertOtherXferOptions
        MOVS     r0,#9
        LSLS     r0,r0,#10
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
|L20.222|
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        B        |L20.30|
        B        |L20.246|
|L20.246|
        MOVS     r0,#2
        B        |L20.30|
        ENDP


        AREA ||i.HAL_SMBUS_Master_Transmit_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_Master_Transmit_IT PROC
        PUSH     {r0-r7,lr}
        SUB      sp,sp,#4
        MOV      r4,r0
        MOV      r6,r2
        MOV      r5,r3
        LDR      r7,[sp,#0x28]
        LDR      r0,[r4,#0x48]
        CMP      r0,#1
        BNE      |L21.272|
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L21.34|
        MOVS     r0,#2
|L21.30|
        ADD      sp,sp,#0x14
        POP      {r4-r7,pc}
|L21.34|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0x12
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        STR      r6,[r4,#0x34]
        STRH     r5,[r4,#0x3a]
        STR      r7,[r4,#0x3c]
        LDR      r0,[r4,#0x34]
        CMP      r0,#0
        BNE      |L21.70|
        LDR      r0,[r4,#0x3c]
        LSLS     r1,r1,#25
        BICS     r0,r0,r1
        STR      r0,[r4,#0x3c]
|L21.70|
        CMP      r5,#0xff
        BLS      |L21.80|
        MOVS     r0,#0xff
        STRH     r0,[r4,#0x38]
        B        |L21.82|
|L21.80|
        STRH     r5,[r4,#0x38]
|L21.82|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0xff
        BNE      |L21.130|
        LDRH     r0,[r4,#0x38]
        LDRH     r1,[r4,#0x3a]
        CMP      r0,r1
        BGE      |L21.130|
        MOVS     r0,#1
        LSLS     r0,r0,#13
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
        B        |L21.248|
|L21.130|
        LDR      r0,[r4,#0x40]
        CMP      r0,#0x12
        BNE      |L21.196|
        LDR      r0,[r4,#0x3c]
        CMP      r0,#0xaa
        BEQ      |L21.168|
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#0x55
        LSLS     r1,r1,#17
        CMP      r0,r1
        BEQ      |L21.168|
        LDR      r0,[r4,#0x3c]
        ASRS     r1,r1,#8
        CMP      r0,r1
        BEQ      |L21.168|
        LDR      r0,[r4,#0x3c]
        LSLS     r1,r1,#16
        CMP      r0,r1
        BNE      |L21.172|
|L21.168|
        MOVS     r0,#1
        B        |L21.174|
|L21.172|
        MOVS     r0,#0
|L21.174|
        CMP      r0,#0
        BNE      |L21.196|
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
        B        |L21.222|
|L21.196|
        MOV      r0,r4
        BL       SMBUS_ConvertOtherXferOptions
        MOVS     r0,#1
        LSLS     r0,r0,#13
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r0,r4
        LDR      r1,[sp,#8]
        BL       SMBUS_TransferConfig
|L21.222|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L21.248|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
|L21.248|
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        B        |L21.30|
        B        |L21.272|
|L21.272|
        MOVS     r0,#2
        B        |L21.30|
        ENDP


        AREA ||i.HAL_SMBUS_MspDeInit||, CODE, READONLY, ALIGN=1

HAL_SMBUS_MspDeInit PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_MspInit||, CODE, READONLY, ALIGN=1

HAL_SMBUS_MspInit PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_SlaveRxCpltCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_SlaveRxCpltCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_SlaveTxCpltCallback||, CODE, READONLY, ALIGN=1

HAL_SMBUS_SlaveTxCpltCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_SMBUS_Slave_Receive_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_Slave_Receive_IT PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOV      r5,r2
        MOV      r7,r3
        LDR      r0,[r4,#0x48]
        CMP      r0,#8
        BNE      |L26.210|
        CMP      r6,#0
        BEQ      |L26.24|
        CMP      r5,#0
        BNE      |L26.28|
|L26.24|
        MOVS     r0,#1
|L26.26|
        POP      {r3-r7,pc}
|L26.28|
        MOVS     r1,#0xfc
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L26.50|
        MOVS     r0,#2
        B        |L26.26|
|L26.50|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x42
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        STR      r6,[r4,#0x34]
        STRH     r5,[r4,#0x38]
        STRH     r5,[r4,#0x3a]
        STR      r7,[r4,#0x3c]
        MOV      r0,r4
        BL       SMBUS_ConvertOtherXferOptions
        LDRH     r0,[r4,#0x38]
        CMP      r0,#1
        BEQ      |L26.138|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#2
        BNE      |L26.158|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L26.158|
|L26.138|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        B        |L26.182|
|L26.158|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#24
        ORRS     r0,r0,r1
        MOV      r3,r0
        MOVS     r2,#1
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
|L26.182|
        MOVS     r0,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r1,#0xfc
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        B        |L26.26|
|L26.210|
        MOVS     r0,#1
        B        |L26.26|
        ENDP


        AREA ||i.HAL_SMBUS_Slave_Transmit_IT||, CODE, READONLY, ALIGN=1

HAL_SMBUS_Slave_Transmit_IT PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOV      r5,r2
        MOV      r7,r3
        LDR      r0,[r4,#0x48]
        CMP      r0,#8
        BNE      |L27.242|
        CMP      r6,#0
        BEQ      |L27.24|
        CMP      r5,#0
        BNE      |L27.28|
|L27.24|
        MOVS     r0,#1
|L27.26|
        POP      {r3-r7,pc}
|L27.28|
        MOVS     r1,#0xfa
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L27.50|
        MOVS     r0,#2
        B        |L27.26|
|L27.50|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x32
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x48]
        MOVS     r0,#0
        STR      r0,[r4,#0x4c]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#16
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        STR      r6,[r4,#0x34]
        STRH     r5,[r4,#0x3a]
        STR      r7,[r4,#0x3c]
        MOV      r0,r4
        BL       SMBUS_ConvertOtherXferOptions
        CMP      r5,#0xff
        BLS      |L27.120|
        MOVS     r0,#0xff
        STRH     r0,[r4,#0x38]
        B        |L27.122|
|L27.120|
        STRH     r5,[r4,#0x38]
|L27.122|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0xff
        BNE      |L27.168|
        LDRH     r0,[r4,#0x38]
        LDRH     r1,[r4,#0x3a]
        CMP      r0,r1
        BGE      |L27.168|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        B        |L27.212|
|L27.168|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L27.212|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
|L27.212|
        MOVS     r0,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r1,#0xfa
        MOV      r0,r4
        BL       SMBUS_Enable_IRQ
        MOVS     r0,#0
        B        |L27.26|
        B        |L27.242|
|L27.242|
        MOVS     r0,#1
        B        |L27.26|
        ENDP


        AREA ||i.SMBUS_ConvertOtherXferOptions||, CODE, READONLY, ALIGN=1

SMBUS_ConvertOtherXferOptions PROC
        LDR      r1,[r0,#0x3c]
        CMP      r1,#0xaa
        BNE      |L28.12|
        MOVS     r1,#0
        STR      r1,[r0,#0x3c]
        B        |L28.64|
|L28.12|
        LDR      r1,[r0,#0x3c]
        MOVS     r2,#0x55
        LSLS     r2,r2,#9
        CMP      r1,r2
        BNE      |L28.30|
        MOVS     r1,#1
        LSLS     r1,r1,#26
        STR      r1,[r0,#0x3c]
        B        |L28.64|
|L28.30|
        LDR      r1,[r0,#0x3c]
        MOVS     r2,#0x55
        LSLS     r2,r2,#17
        CMP      r1,r2
        BNE      |L28.48|
        MOVS     r1,#1
        LSLS     r1,r1,#25
        STR      r1,[r0,#0x3c]
        B        |L28.64|
|L28.48|
        LDR      r1,[r0,#0x3c]
        MOVS     r2,#0x55
        LSLS     r2,r2,#25
        CMP      r1,r2
        BNE      |L28.64|
        MOVS     r1,#3
        LSLS     r1,r1,#25
        STR      r1,[r0,#0x3c]
|L28.64|
        BX       lr
        ENDP


        AREA ||i.SMBUS_Disable_IRQ||, CODE, READONLY, ALIGN=1

SMBUS_Disable_IRQ PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        MOV      r3,r1
        MOVS     r1,#0
        MOVS     r0,#0x80
        ANDS     r0,r0,r3
        CMP      r0,#0x80
        BNE      |L29.26|
        LDR      r0,[r2,#0x48]
        CMP      r0,#1
        BNE      |L29.26|
        MOVS     r0,#0x80
        ORRS     r1,r1,r0
|L29.26|
        MOVS     r0,#0xf2
        ANDS     r0,r0,r3
        CMP      r0,#0xf2
        BNE      |L29.80|
        MOVS     r0,#0x42
        ORRS     r1,r1,r0
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#1
        LSLS     r4,r4,#22
        ANDS     r0,r0,r4
        CMP      r0,#0
        BNE      |L29.66|
        LDR      r0,[r2,#0x48]
        MOVS     r4,#8
        ANDS     r0,r0,r4
        CMP      r0,#8
        BEQ      |L29.66|
        MOVS     r0,#0x80
        ORRS     r1,r1,r0
|L29.66|
        LDR      r0,[r2,#0x48]
        MOVS     r4,#8
        ANDS     r0,r0,r4
        CMP      r0,#8
        BEQ      |L29.80|
        MOVS     r0,#0x30
        ORRS     r1,r1,r0
|L29.80|
        MOVS     r0,#0xd4
        ANDS     r0,r0,r3
        CMP      r0,#0xd4
        BNE      |L29.134|
        MOVS     r0,#0x44
        ORRS     r1,r1,r0
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#1
        LSLS     r4,r4,#22
        ANDS     r0,r0,r4
        CMP      r0,#0
        BNE      |L29.120|
        LDR      r0,[r2,#0x48]
        MOVS     r4,#8
        ANDS     r0,r0,r4
        CMP      r0,#8
        BEQ      |L29.120|
        MOVS     r0,#0x80
        ORRS     r1,r1,r0
|L29.120|
        LDR      r0,[r2,#0x48]
        MOVS     r4,#8
        ANDS     r0,r0,r4
        CMP      r0,#8
        BEQ      |L29.134|
        MOVS     r0,#0x30
        ORRS     r1,r1,r0
|L29.134|
        MOVS     r0,#0x38
        ANDS     r0,r0,r3
        CMP      r0,#0x38
        BNE      |L29.162|
        ORRS     r1,r1,r0
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#1
        LSLS     r4,r4,#22
        ANDS     r0,r0,r4
        CMP      r0,#0
        BNE      |L29.162|
        MOVS     r0,#0x80
        ORRS     r1,r1,r0
|L29.162|
        LDR      r0,[r2,#0]
        LDR      r0,[r0,#0]
        BICS     r0,r0,r1
        LDR      r4,[r2,#0]
        STR      r0,[r4,#0]
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP


        AREA ||i.SMBUS_Enable_IRQ||, CODE, READONLY, ALIGN=1

SMBUS_Enable_IRQ PROC
        PUSH     {r4,lr}
        MOV      r3,r0
        MOVS     r2,#0
        MOVS     r0,#0x80
        ANDS     r0,r0,r1
        CMP      r0,#0x80
        BNE      |L30.16|
        ORRS     r2,r2,r0
|L30.16|
        MOVS     r0,#0x38
        ANDS     r0,r0,r1
        CMP      r0,#0x38
        BNE      |L30.28|
        MOVS     r0,#0xb8
        ORRS     r2,r2,r0
|L30.28|
        MOVS     r0,#0xf2
        ANDS     r0,r0,r1
        CMP      r0,#0xf2
        BNE      |L30.38|
        ORRS     r2,r2,r0
|L30.38|
        MOVS     r0,#0xd4
        ANDS     r0,r0,r1
        CMP      r0,#0xd4
        BNE      |L30.50|
        MOVS     r0,#0xf4
        ORRS     r2,r2,r0
|L30.50|
        LDR      r0,[r3,#0]
        LDR      r0,[r0,#0]
        ORRS     r0,r0,r2
        LDR      r4,[r3,#0]
        STR      r0,[r4,#0]
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP


        AREA ||i.SMBUS_ITErrorHandler||, CODE, READONLY, ALIGN=1

SMBUS_ITErrorHandler PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        LDR      r0,[r4,#0]
        LDR      r6,[r0,#0x18]
        LDR      r0,[r4,#0]
        LDR      r5,[r0,#0]
        MOVS     r0,#0xff
        ADDS     r0,#1
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.44|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.44|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#1
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.44|
        MOVS     r0,#1
        LSLS     r0,r0,#10
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.76|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.76|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#8
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#7
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.76|
        MOVS     r0,#1
        LSLS     r0,r0,#9
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.108|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.108|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#2
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.108|
        MOVS     r0,#1
        LSLS     r0,r0,#12
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.140|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.140|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#0x20
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#7
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.140|
        MOVS     r0,#1
        LSLS     r0,r0,#13
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.172|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.172|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#0x40
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#7
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.172|
        MOVS     r0,#1
        LSLS     r0,r0,#11
        ANDS     r0,r0,r6
        CMP      r0,#0
        BEQ      |L31.204|
        MOVS     r0,#0x80
        ANDS     r0,r0,r5
        CMP      r0,#0
        BEQ      |L31.204|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#0x80
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        LSLS     r0,r1,#4
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
|L31.204|
        LDR      r0,[r4,#0x4c]
        CMP      r0,#0
        BEQ      |L31.260|
        LDR      r0,[r4,#0x4c]
        CMP      r0,#4
        BEQ      |L31.260|
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        CMP      r0,#0x40
        BEQ      |L31.254|
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x32
        ANDS     r0,r0,r1
        CMP      r0,#0x32
        BEQ      |L31.246|
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x42
        ANDS     r0,r0,r1
        CMP      r0,#0x42
        BNE      |L31.254|
|L31.246|
        MOVS     r0,#1
        STR      r0,[r4,#0x40]
        MOVS     r0,#8
        STR      r0,[r4,#0x48]
|L31.254|
        MOV      r0,r4
        BL       HAL_SMBUS_ErrorCallback
|L31.260|
        POP      {r4-r6,pc}
        ENDP


        AREA ||i.SMBUS_Master_ISR||, CODE, READONLY, ALIGN=2

SMBUS_Master_ISR PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L32.18|
        MOVS     r0,#2
|L32.16|
        POP      {r3-r5,pc}
|L32.18|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L32.72|
        MOVS     r0,#0x10
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#4
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_ErrorCallback
|L32.70|
        B        |L32.716|
|L32.72|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        LSRS     r0,r0,#5
        CMP      r0,#0
        BEQ      |L32.274|
        MOV      r0,r4
        BL       SMBUS_ITErrorHandler
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x12
        BNE      |L32.172|
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LDR      r1,|L32.732|
        ANDS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        LSRS     r0,r0,#1
        LSLS     r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOVS     r0,#1
        STR      r0,[r4,#0x40]
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        MOV      r0,r4
        BL       HAL_SMBUS_MasterTxCpltCallback
        B        |L32.716|
|L32.172|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x22
        BNE      |L32.70|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#4
        ANDS     r0,r0,r1
        LSRS     r0,r0,#2
        CMP      r0,#0
        BEQ      |L32.224|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x24]
        UXTB     r1,r0
        LDR      r2,[r4,#0x34]
        ADDS     r0,r2,#1
        STR      r0,[r4,#0x34]
        STRB     r1,[r2,#0]
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0
        BEQ      |L32.224|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
|L32.224|
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LDR      r1,|L32.732|
        ANDS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        MOVS     r0,#1
        STR      r0,[r4,#0x40]
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_MasterRxCpltCallback
        B        |L32.716|
|L32.274|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#4
        ANDS     r0,r0,r1
        LSRS     r0,r0,#2
        CMP      r0,#0
        BEQ      |L32.316|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x24]
        UXTB     r1,r0
        LDR      r2,[r4,#0x34]
        ADDS     r0,r2,#1
        STR      r0,[r4,#0x34]
        STRB     r1,[r2,#0]
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        B        |L32.716|
|L32.316|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        LSRS     r0,r0,#1
        CMP      r0,#0
        BEQ      |L32.356|
        LDR      r1,[r4,#0x34]
        ADDS     r0,r1,#1
        STR      r0,[r4,#0x34]
        LDRB     r0,[r1,#0]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x28]
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        B        |L32.716|
|L32.356|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x80
        ANDS     r0,r0,r1
        LSRS     r0,r0,#7
        CMP      r0,#0
        BEQ      |L32.584|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0
        BNE      |L32.478|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BEQ      |L32.478|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LSLS     r5,r0,#22
        LSRS     r5,r5,#22
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0xff
        BLS      |L32.428|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        LSLS     r1,r1,#19
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        MOVS     r2,#0xff
        MOV      r1,r5
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        MOVS     r0,#0xff
        STRH     r0,[r4,#0x38]
        B        |L32.716|
|L32.428|
        LDRH     r0,[r4,#0x3a]
        STRH     r0,[r4,#0x38]
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOV      r1,r5
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L32.716|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        B        |L32.716|
|L32.478|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0
        BNE      |L32.716|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BNE      |L32.716|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#25
        ANDS     r0,r0,r1
        CMP      r0,r1
        BEQ      |L32.716|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x12
        BNE      |L32.544|
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_MasterTxCpltCallback
        B        |L32.716|
|L32.544|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x22
        BNE      |L32.716|
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_MasterRxCpltCallback
        B        |L32.716|
|L32.584|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x40
        ANDS     r0,r0,r1
        LSRS     r0,r0,#6
        CMP      r0,#0
        BEQ      |L32.716|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BNE      |L32.716|
        LDR      r0,[r4,#0x34]
        CMP      r0,#0
        BNE      |L32.624|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LSLS     r1,r1,#8
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        B        |L32.716|
|L32.624|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#25
        ANDS     r0,r0,r1
        CMP      r0,r1
        BEQ      |L32.716|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x12
        BNE      |L32.678|
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_MasterTxCpltCallback
        B        |L32.716|
|L32.678|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0x22
        BNE      |L32.716|
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_MasterRxCpltCallback
|L32.716|
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0
        B        |L32.16|
        ENDP

        DCW      0x0000
|L32.732|
        DCD      0xfe00e800

        AREA ||i.SMBUS_Slave_ISR||, CODE, READONLY, ALIGN=2

SMBUS_Slave_ISR PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOVS     r5,#0
        MOVS     r6,#0
        NOP      
        MOVS     r0,#0x44
        LDRB     r0,[r0,r4]
        CMP      r0,#1
        BNE      |L33.22|
        MOVS     r0,#2
|L33.20|
        POP      {r3-r7,pc}
|L33.22|
        MOVS     r1,#1
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x10
        ANDS     r0,r0,r1
        LSRS     r0,r0,#4
        CMP      r0,#0
        BEQ      |L33.126|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BNE      |L33.66|
        MOVS     r0,#0x10
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        B        |L33.584|
|L33.66|
        MOVS     r0,#0x10
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x32
        BICS     r0,r0,r1
        STR      r0,[r4,#0x48]
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x42
        BICS     r0,r0,r1
        STR      r0,[r4,#0x48]
        MOVS     r1,#0xf6
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x4c]
        MOVS     r1,#4
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x4c]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_ErrorCallback
        B        |L33.584|
|L33.126|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#8
        ANDS     r0,r0,r1
        LSRS     r0,r0,#3
        CMP      r0,#0
        BEQ      |L33.196|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        LSLS     r1,r1,#13
        ANDS     r0,r0,r1
        LSRS     r5,r0,#16
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x7f
        LSLS     r1,r1,#17
        ANDS     r0,r0,r1
        LSRS     r6,r0,#17
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        MOVS     r1,#8
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r2,r6
        MOV      r1,r5
        MOV      r0,r4
        BL       HAL_SMBUS_AddrCallback
        B        |L33.584|
|L33.196|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#4
        ANDS     r0,r0,r1
        LSRS     r0,r0,#2
        CMP      r0,#0
        BNE      |L33.224|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x80
        ANDS     r0,r0,r1
        LSRS     r0,r0,#7
        CMP      r0,#0
        BEQ      |L33.476|
|L33.224|
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x42
        ANDS     r0,r0,r1
        CMP      r0,#0x42
        BNE      |L33.382|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x24]
        UXTB     r1,r0
        LDR      r2,[r4,#0x34]
        ADDS     r0,r2,#1
        STR      r0,[r4,#0x34]
        STRB     r1,[r2,#0]
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#1
        BNE      |L33.294|
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#24
        BICS     r0,r0,r1
        STR      r0,[r4,#0x3c]
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        MOVS     r2,#1
        MOV      r1,r0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        B        |L33.584|
|L33.294|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BNE      |L33.338|
        MOVS     r1,#0xd4
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x42
        BICS     r0,r0,r1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_SlaveRxCpltCallback
        B        |L33.584|
|L33.338|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        MOVS     r2,#1
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        BICS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        B        |L33.584|
|L33.382|
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x32
        ANDS     r0,r0,r1
        CMP      r0,#0x32
        BNE      |L33.584|
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0
        BNE      |L33.584|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BEQ      |L33.584|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0xff
        BLS      |L33.444|
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,[r4,#0x3c]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        ANDS     r0,r0,r1
        ASRS     r1,r1,#2
        ORRS     r0,r0,r1
        MOV      r3,r0
        MOVS     r2,#0xff
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        MOVS     r0,#0xff
        STRH     r0,[r4,#0x38]
        B        |L33.584|
|L33.444|
        LDRH     r0,[r4,#0x3a]
        STRH     r0,[r4,#0x38]
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r3,[r4,#0x3c]
        LDRH     r0,[r4,#0x38]
        UXTB     r2,r0
        MOVS     r1,#0
        MOV      r0,r4
        BL       SMBUS_TransferConfig
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#26
        B        |L33.478|
|L33.476|
        B        |L33.498|
|L33.478|
        ANDS     r0,r0,r1
        CMP      r0,#0
        BEQ      |L33.584|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        B        |L33.584|
|L33.498|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#2
        ANDS     r0,r0,r1
        LSRS     r0,r0,#1
        CMP      r0,#0
        BEQ      |L33.584|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BEQ      |L33.542|
        LDR      r1,[r4,#0x34]
        ADDS     r0,r1,#1
        STR      r0,[r4,#0x34]
        LDRB     r0,[r1,#0]
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x28]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
|L33.542|
        LDRH     r0,[r4,#0x3a]
        CMP      r0,#0
        BNE      |L33.584|
        MOVS     r1,#0xf2
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        LDR      r0,[r4,#0x48]
        MOVS     r1,#0x32
        BICS     r0,r0,r1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_SlaveTxCpltCallback
|L33.584|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#0x20
        ANDS     r0,r0,r1
        LSRS     r0,r0,#5
        CMP      r0,#0
        BEQ      |L33.736|
        LDR      r0,[r4,#0x48]
        MOVS     r1,#8
        ANDS     r0,r0,r1
        CMP      r0,#8
        BNE      |L33.736|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        MOVS     r1,#4
        ANDS     r0,r0,r1
        LSRS     r0,r0,#2
        CMP      r0,#0
        BEQ      |L33.654|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x24]
        UXTB     r1,r0
        LDR      r2,[r4,#0x34]
        ADDS     r0,r2,#1
        STR      r0,[r4,#0x34]
        STRB     r1,[r2,#0]
        LDRH     r0,[r4,#0x38]
        CMP      r0,#0
        BEQ      |L33.654|
        LDRH     r0,[r4,#0x38]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x38]
        LDRH     r0,[r4,#0x3a]
        SUBS     r0,r0,#1
        STRH     r0,[r4,#0x3a]
|L33.654|
        MOVS     r1,#0xf6
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        MOVS     r1,#0x38
        MOV      r0,r4
        BL       SMBUS_Disable_IRQ
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        MOVS     r1,#1
        LSLS     r1,r1,#15
        ORRS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#4]
        LDR      r1,|L33.752|
        ANDS     r0,r0,r1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#4]
        MOVS     r0,#0x20
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        MOVS     r0,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x1c]
        MOVS     r0,#0
        STR      r0,[r4,#0x3c]
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOV      r0,r4
        BL       HAL_SMBUS_ListenCpltCallback
|L33.736|
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#0
        B        |L33.20|
        ENDP

        DCW      0x0000
|L33.752|
        DCD      0xfe00e800

        AREA ||i.SMBUS_TransferConfig||, CODE, READONLY, ALIGN=2

SMBUS_TransferConfig PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r1
        MOVS     r1,#0
        LDR      r5,[r0,#0]
        LDR      r1,[r5,#4]
        LDR      r5,|L34.44|
        ANDS     r1,r1,r5
        LSLS     r5,r4,#22
        LSRS     r5,r5,#22
        LSLS     r6,r2,#16
        MOVS     r7,#0xff
        LSLS     r7,r7,#16
        ANDS     r6,r6,r7
        ORRS     r5,r5,r6
        ORRS     r5,r5,r3
        LDR      r6,[sp,#0x14]
        ORRS     r5,r5,r6
        ORRS     r1,r1,r5
        LDR      r5,[r0,#0]
        STR      r1,[r5,#4]
        POP      {r4-r7,pc}
        ENDP

        DCW      0x0000
|L34.44|
        DCD      0xf8009800

        AREA ||i.SMBUS_WaitOnFlagUntilTimeout||, CODE, READONLY, ALIGN=1

SMBUS_WaitOnFlagUntilTimeout PROC
        PUSH     {r0-r7,lr}
        SUB      sp,sp,#4
        MOV      r4,r0
        MOV      r6,r1
        MOV      r5,r3
        BL       HAL_GetTick
        MOV      r7,r0
        LDR      r0,[sp,#0xc]
        CMP      r0,#0
        BNE      |L35.98|
        B        |L35.68|
|L35.24|
        ADDS     r0,r5,#1
        CMP      r0,#0
        BEQ      |L35.68|
        CMP      r5,#0
        BEQ      |L35.44|
        BL       HAL_GetTick
        SUBS     r0,r0,r7
        CMP      r0,r5
        BLS      |L35.68|
|L35.44|
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#3
|L35.64|
        ADD      sp,sp,#0x14
        POP      {r4-r7,pc}
|L35.68|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        LSLS     r1,r6,#15
        LSRS     r1,r1,#15
        ANDS     r0,r0,r1
        LSLS     r1,r6,#15
        LSRS     r1,r1,#15
        CMP      r0,r1
        BNE      |L35.90|
        MOVS     r0,#1
        B        |L35.92|
|L35.90|
        MOVS     r0,#0
|L35.92|
        CMP      r0,#0
        BEQ      |L35.24|
        B        |L35.170|
|L35.98|
        B        |L35.142|
|L35.100|
        ADDS     r0,r5,#1
        CMP      r0,#0
        BEQ      |L35.142|
        CMP      r5,#0
        BEQ      |L35.120|
        BL       HAL_GetTick
        SUBS     r0,r0,r7
        CMP      r0,r5
        BLS      |L35.142|
|L35.120|
        LDR      r0,[r4,#0x48]
        STR      r0,[r4,#0x40]
        MOVS     r0,#1
        STR      r0,[r4,#0x48]
        NOP      
        MOVS     r1,#0
        MOVS     r0,#0x44
        STRB     r1,[r0,r4]
        NOP      
        MOVS     r0,#3
        B        |L35.64|
|L35.142|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x18]
        LSLS     r1,r6,#15
        LSRS     r1,r1,#15
        ANDS     r0,r0,r1
        LSLS     r1,r6,#15
        LSRS     r1,r1,#15
        CMP      r0,r1
        BNE      |L35.164|
        MOVS     r0,#1
        B        |L35.166|
|L35.164|
        MOVS     r0,#0
|L35.166|
        CMP      r0,#0
        BNE      |L35.100|
|L35.170|
        MOVS     r0,#0
        B        |L35.64|
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "C:\\Keil_v5\\ARM\\PACK\\Keil\\STM32F0xx_DFP\\2.0.0\\Drivers\\STM32F0xx_HAL_Driver\\Src\\stm32f0xx_hal_smbus.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___21_stm32f0xx_hal_smbus_c_0d9f6733____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___21_stm32f0xx_hal_smbus_c_0d9f6733____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___21_stm32f0xx_hal_smbus_c_0d9f6733____REVSH|
#line 478
|__asm___21_stm32f0xx_hal_smbus_c_0d9f6733____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_SMBUS_AddrCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_ConfigAnalogFilter [CODE]
        EXPORT HAL_SMBUS_ConfigDigitalFilter [CODE]
        EXPORT HAL_SMBUS_DeInit [CODE]
        EXPORT HAL_SMBUS_DisableAlert_IT [CODE]
        EXPORT HAL_SMBUS_DisableListen_IT [CODE]
        EXPORT HAL_SMBUS_ER_IRQHandler [CODE]
        EXPORT HAL_SMBUS_EV_IRQHandler [CODE]
        EXPORT HAL_SMBUS_EnableAlert_IT [CODE]
        EXPORT HAL_SMBUS_EnableListen_IT [CODE]
        EXPORT HAL_SMBUS_ErrorCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_GetError [CODE]
        EXPORT HAL_SMBUS_GetState [CODE]
        EXPORT HAL_SMBUS_Init [CODE]
        EXPORT HAL_SMBUS_IsDeviceReady [CODE]
        EXPORT HAL_SMBUS_ListenCpltCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_MasterRxCpltCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_MasterTxCpltCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_Master_Abort_IT [CODE]
        EXPORT HAL_SMBUS_Master_Receive_IT [CODE]
        EXPORT HAL_SMBUS_Master_Transmit_IT [CODE]
        EXPORT HAL_SMBUS_MspDeInit [CODE,WEAK]
        EXPORT HAL_SMBUS_MspInit [CODE,WEAK]
        EXPORT HAL_SMBUS_SlaveRxCpltCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_SlaveTxCpltCallback [CODE,WEAK]
        EXPORT HAL_SMBUS_Slave_Receive_IT [CODE]
        EXPORT HAL_SMBUS_Slave_Transmit_IT [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT HAL_GetTick [CODE]

        KEEP SMBUS_ConvertOtherXferOptions
        KEEP SMBUS_Disable_IRQ
        KEEP SMBUS_Enable_IRQ
        KEEP SMBUS_ITErrorHandler
        KEEP SMBUS_Master_ISR
        KEEP SMBUS_Slave_ISR
        KEEP SMBUS_TransferConfig
        KEEP SMBUS_WaitOnFlagUntilTimeout

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
