; generated by Component: ARM Compiler 5.05 update 1 (build 106) Tool: ArmCC [4d0efa]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\stm32f0xx_hal_flash_ex.o --depend=.\objects\stm32f0xx_hal_flash_ex.d --cpu=Cortex-M0 --apcs=interwork -O0 --diag_suppress=9931 -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE -IC:\Users\Tom\Documents\Projects\Scopy_MVP_Platform\scopy-fpga\mcuapp_stm32f0\RTE\Device\STM32F071VBTx -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0 -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\CMSIS\Device\ST\STM32F0xx\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc -IC:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Inc\Legacy -D__UVISION_VERSION=514 -D_RTE_ -DSTM32F071xB --omf_browse=.\objects\stm32f0xx_hal_flash_ex.crf C:\Keil_v5\ARM\PACK\Keil\STM32F0xx_DFP\2.0.0\Drivers\STM32F0xx_HAL_Driver\Src\stm32f0xx_hal_flash_ex.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.FLASH_MassErase||, CODE, READONLY, ALIGN=2

FLASH_MassErase PROC
        MOVS     r0,#0
        LDR      r1,|L1.32|
        STR      r0,[r1,#0x1c]  ; pFlash
        LDR      r0,|L1.36|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#4
        ORRS     r0,r0,r1
        LDR      r1,|L1.36|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x40
        ORRS     r0,r0,r1
        LDR      r1,|L1.36|
        STR      r0,[r1,#0x10]
        BX       lr
        ENDP

|L1.32|
        DCD      pFlash
|L1.36|
        DCD      0x40022000

        AREA ||i.FLASH_OB_DisableWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_DisableWRP PROC
        PUSH     {r1-r7,lr}
        MOV      r4,r0
        MOVS     r5,#0
        LDR      r6,|L2.208|
        MOV      r7,r6
        MOV      r0,r6
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        BL       FLASH_OB_GetWRP
        ORRS     r4,r4,r0
        UXTB     r6,r4
        MOVS     r0,#0xff
        LSLS     r0,r0,#8
        ANDS     r0,r0,r4
        LSRS     r7,r0,#8
        MOVS     r0,#0xff
        LSLS     r0,r0,#16
        ANDS     r0,r0,r4
        LSRS     r0,r0,#16
        STR      r0,[sp,#4]
        LSRS     r0,r4,#24
        STR      r0,[sp,#0]
        LDR      r0,|L2.212|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
        CMP      r5,#0
        BNE      |L2.204|
        LDR      r1,|L2.216|
        STR      r0,[r1,#0x1c]  ; pFlash
        BL       HAL_FLASHEx_OBErase
        MOV      r5,r0
        CMP      r5,#0
        BNE      |L2.204|
        LDR      r0,|L2.220|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        ORRS     r0,r0,r1
        LDR      r1,|L2.220|
        STR      r0,[r1,#0x10]
        CMP      r6,#0xff
        BEQ      |L2.106|
        LDR      r0,|L2.224|
        LDRH     r0,[r0,#8]
        ORRS     r0,r0,r6
        LDR      r1,|L2.224|
        STRH     r0,[r1,#8]
        LDR      r0,|L2.212|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L2.106|
        CMP      r5,#0
        BNE      |L2.132|
        CMP      r7,#0xff
        BEQ      |L2.132|
        LDR      r0,|L2.224|
        LDRH     r0,[r0,#0xa]
        ORRS     r0,r0,r7
        LDR      r1,|L2.224|
        STRH     r0,[r1,#0xa]
        LDR      r0,|L2.212|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L2.132|
        CMP      r5,#0
        BNE      |L2.162|
        LDR      r0,[sp,#4]
        CMP      r0,#0xff
        BEQ      |L2.162|
        LDR      r0,|L2.224|
        LDRH     r0,[r0,#0xc]
        LDR      r1,[sp,#4]
        ORRS     r0,r0,r1
        LDR      r1,|L2.224|
        STRH     r0,[r1,#0xc]
        LDR      r0,|L2.212|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L2.162|
        CMP      r5,#0
        BNE      |L2.192|
        LDR      r0,[sp,#0]
        CMP      r0,#0xff
        BEQ      |L2.192|
        LDR      r0,|L2.224|
        LDRH     r0,[r0,#0xe]
        LDR      r1,[sp,#0]
        ORRS     r0,r0,r1
        LDR      r1,|L2.224|
        STRH     r0,[r1,#0xe]
        LDR      r0,|L2.212|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L2.192|
        LDR      r0,|L2.220|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L2.220|
        STR      r0,[r1,#0x10]
|L2.204|
        MOV      r0,r5
        POP      {r1-r7,pc}
        ENDP

|L2.208|
        DCD      0x0000ffff
|L2.212|
        DCD      0x0000c350
|L2.216|
        DCD      pFlash
|L2.220|
        DCD      0x40022000
|L2.224|
        DCD      0x1ffff800

        AREA ||i.FLASH_OB_EnableWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_EnableWRP PROC
        PUSH     {r1-r7,lr}
        MOV      r4,r0
        MOVS     r5,#0
        LDR      r6,|L3.212|
        MOV      r7,r6
        MOV      r0,r6
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        BL       FLASH_OB_GetWRP
        MVNS     r0,r0
        ORRS     r0,r0,r4
        MVNS     r4,r0
        UXTB     r6,r4
        MOVS     r0,#0xff
        LSLS     r0,r0,#8
        ANDS     r0,r0,r4
        LSRS     r7,r0,#8
        MOVS     r0,#0xff
        LSLS     r0,r0,#16
        ANDS     r0,r0,r4
        LSRS     r0,r0,#16
        STR      r0,[sp,#4]
        LSRS     r0,r4,#24
        STR      r0,[sp,#0]
        LDR      r0,|L3.216|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
        CMP      r5,#0
        BNE      |L3.208|
        LDR      r1,|L3.220|
        STR      r0,[r1,#0x1c]  ; pFlash
        BL       HAL_FLASHEx_OBErase
        MOV      r5,r0
        CMP      r5,#0
        BNE      |L3.208|
        LDR      r0,|L3.224|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        ORRS     r0,r0,r1
        LDR      r1,|L3.224|
        STR      r0,[r1,#0x10]
        CMP      r6,#0xff
        BEQ      |L3.110|
        LDR      r0,|L3.228|
        LDRH     r0,[r0,#8]
        ANDS     r0,r0,r6
        LDR      r1,|L3.228|
        STRH     r0,[r1,#8]
        LDR      r0,|L3.216|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L3.110|
        CMP      r5,#0
        BNE      |L3.136|
        CMP      r7,#0xff
        BEQ      |L3.136|
        LDR      r0,|L3.228|
        LDRH     r0,[r0,#0xa]
        ANDS     r0,r0,r7
        LDR      r1,|L3.228|
        STRH     r0,[r1,#0xa]
        LDR      r0,|L3.216|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L3.136|
        CMP      r5,#0
        BNE      |L3.166|
        LDR      r0,[sp,#4]
        CMP      r0,#0xff
        BEQ      |L3.166|
        LDR      r0,|L3.228|
        LDRH     r0,[r0,#0xc]
        LDR      r1,[sp,#4]
        ANDS     r0,r0,r1
        LDR      r1,|L3.228|
        STRH     r0,[r1,#0xc]
        LDR      r0,|L3.216|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L3.166|
        CMP      r5,#0
        BNE      |L3.196|
        LDR      r0,[sp,#0]
        CMP      r0,#0xff
        BEQ      |L3.196|
        LDR      r0,|L3.228|
        LDRH     r0,[r0,#0xe]
        LDR      r1,[sp,#0]
        ANDS     r0,r0,r1
        LDR      r1,|L3.228|
        STRH     r0,[r1,#0xe]
        LDR      r0,|L3.216|
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
|L3.196|
        LDR      r0,|L3.224|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L3.224|
        STR      r0,[r1,#0x10]
|L3.208|
        MOV      r0,r5
        POP      {r1-r7,pc}
        ENDP

|L3.212|
        DCD      0x0000ffff
|L3.216|
        DCD      0x0000c350
|L3.220|
        DCD      pFlash
|L3.224|
        DCD      0x40022000
|L3.228|
        DCD      0x1ffff800

        AREA ||i.FLASH_OB_GetRDP||, CODE, READONLY, ALIGN=2

FLASH_OB_GetRDP PROC
        MOVS     r1,#0
        LDR      r0,|L4.32|
        LDR      r0,[r0,#0x1c]
        MOVS     r2,#6
        ANDS     r0,r0,r2
        MOV      r1,r0
        CMP      r1,#2
        BNE      |L4.20|
        MOVS     r0,#0xbb
|L4.18|
        BX       lr
|L4.20|
        CMP      r1,#4
        BNE      |L4.28|
        MOVS     r0,#0xcc
        B        |L4.18|
|L4.28|
        MOVS     r0,#0xaa
        B        |L4.18|
        ENDP

|L4.32|
        DCD      0x40022000

        AREA ||i.FLASH_OB_GetUser||, CODE, READONLY, ALIGN=2

FLASH_OB_GetUser PROC
        LDR      r0,|L5.16|
        LDR      r0,[r0,#0x1c]
        MOVS     r1,#0x77
        LSLS     r1,r1,#8
        ANDS     r0,r0,r1
        LSRS     r0,r0,#8
        BX       lr
        ENDP

        DCW      0x0000
|L5.16|
        DCD      0x40022000

        AREA ||i.FLASH_OB_GetWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_GetWRP PROC
        LDR      r0,|L6.8|
        LDR      r0,[r0,#0x20]
        BX       lr
        ENDP

        DCW      0x0000
|L6.8|
        DCD      0x40022000

        AREA ||i.FLASH_OB_ProgramData||, CODE, READONLY, ALIGN=2

FLASH_OB_ProgramData PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOVS     r6,#1
        LDR      r0,|L7.64|
        BL       FLASH_WaitForLastOperation
        MOV      r6,r0
        CMP      r6,#0
        BNE      |L7.58|
        LDR      r1,|L7.68|
        STR      r0,[r1,#0x1c]  ; pFlash
        LDR      r0,|L7.72|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        ORRS     r0,r0,r1
        LDR      r1,|L7.72|
        STR      r0,[r1,#0x10]
        STRH     r5,[r4,#0]
        LDR      r0,|L7.64|
        BL       FLASH_WaitForLastOperation
        MOV      r6,r0
        LDR      r0,|L7.72|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L7.72|
        STR      r0,[r1,#0x10]
|L7.58|
        MOV      r0,r6
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L7.64|
        DCD      0x0000c350
|L7.68|
        DCD      pFlash
|L7.72|
        DCD      0x40022000

        AREA ||i.FLASH_OB_RDP_LevelConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_RDP_LevelConfig PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r4,#0
        LDR      r0,|L8.112|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L8.106|
        LDR      r1,|L8.116|
        STR      r0,[r1,#0x1c]  ; pFlash
        LDR      r0,|L8.120|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x20
        ORRS     r0,r0,r1
        LDR      r1,|L8.120|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x40
        ORRS     r0,r0,r1
        LDR      r1,|L8.120|
        STR      r0,[r1,#0x10]
        LDR      r0,|L8.112|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        LDR      r0,|L8.120|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x20
        BICS     r0,r0,r1
        LDR      r1,|L8.120|
        STR      r0,[r1,#0x10]
        CMP      r4,#0
        BNE      |L8.106|
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        ORRS     r0,r0,r1
        LDR      r1,|L8.120|
        STR      r0,[r1,#0x10]
        LDR      r0,|L8.124|
        STRH     r5,[r0,#0]
        LDR      r0,|L8.112|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        LDR      r0,|L8.120|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L8.120|
        STR      r0,[r1,#0x10]
|L8.106|
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L8.112|
        DCD      0x0000c350
|L8.116|
        DCD      pFlash
|L8.120|
        DCD      0x40022000
|L8.124|
        DCD      0x1ffff800

        AREA ||i.FLASH_OB_UserConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_UserConfig PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r4,#0
        LDR      r0,|L9.68|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L9.62|
        LDR      r1,|L9.72|
        STR      r0,[r1,#0x1c]  ; pFlash
        LDR      r0,|L9.76|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        ORRS     r0,r0,r1
        LDR      r1,|L9.76|
        STR      r0,[r1,#0x10]
        MOVS     r0,#0x88
        ORRS     r0,r0,r5
        LDR      r1,|L9.80|
        STRH     r0,[r1,#2]
        LDR      r0,|L9.68|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        LDR      r0,|L9.76|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        LDR      r1,|L9.76|
        STR      r0,[r1,#0x10]
|L9.62|
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L9.68|
        DCD      0x0000c350
|L9.72|
        DCD      pFlash
|L9.76|
        DCD      0x40022000
|L9.80|
        DCD      0x1ffff800

        AREA ||i.FLASH_PageErase||, CODE, READONLY, ALIGN=2

FLASH_PageErase PROC
        MOVS     r1,#0
        LDR      r2,|L10.36|
        STR      r1,[r2,#0x1c]  ; pFlash
        LDR      r1,|L10.40|
        LDR      r1,[r1,#0x10]
        MOVS     r2,#2
        ORRS     r1,r1,r2
        LDR      r2,|L10.40|
        STR      r1,[r2,#0x10]
        MOV      r1,r2
        STR      r0,[r1,#0x14]
        LDR      r1,[r1,#0x10]
        MOVS     r2,#0x40
        ORRS     r1,r1,r2
        LDR      r2,|L10.40|
        STR      r1,[r2,#0x10]
        BX       lr
        ENDP

        DCW      0x0000
|L10.36|
        DCD      pFlash
|L10.40|
        DCD      0x40022000

        AREA ||i.HAL_FLASHEx_Erase||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_Erase PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOVS     r7,#1
        MOVS     r5,#0
        NOP      
        LDR      r0,|L11.160|
        LDRB     r0,[r0,#0x18]  ; pFlash
        CMP      r0,#1
        BNE      |L11.24|
        MOVS     r0,#2
|L11.22|
        POP      {r3-r7,pc}
|L11.24|
        MOVS     r0,#1
        LDR      r1,|L11.160|
        STRB     r0,[r1,#0x18]
        NOP      
        LDR      r0,[r4,#0]
        CMP      r0,#1
        BNE      |L11.74|
        LDR      r0,|L11.164|
        BL       FLASH_WaitForLastOperation
        CMP      r0,#0
        BNE      |L11.146|
        BL       FLASH_MassErase
        LDR      r0,|L11.164|
        BL       FLASH_WaitForLastOperation
        MOV      r7,r0
        LDR      r0,|L11.168|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#4
        BICS     r0,r0,r1
        LDR      r1,|L11.168|
        STR      r0,[r1,#0x10]
        B        |L11.146|
|L11.74|
        LDR      r0,|L11.164|
        BL       FLASH_WaitForLastOperation
        CMP      r0,#0
        BNE      |L11.146|
        SUBS     r0,r0,#1
        STR      r0,[r6,#0]
        LDR      r5,[r4,#4]
        B        |L11.132|
|L11.92|
        MOV      r0,r5
        BL       FLASH_PageErase
        LDR      r0,|L11.164|
        BL       FLASH_WaitForLastOperation
        MOV      r7,r0
        LDR      r0,|L11.168|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#2
        BICS     r0,r0,r1
        LDR      r1,|L11.168|
        STR      r0,[r1,#0x10]
        CMP      r7,#0
        BEQ      |L11.126|
        STR      r5,[r6,#0]
        B        |L11.144|
|L11.126|
        MOVS     r0,#1
        LSLS     r0,r0,#11
        ADDS     r5,r5,r0
|L11.132|
        LDR      r0,[r4,#8]
        LSLS     r0,r0,#11
        LDR      r1,[r4,#4]
        ADDS     r0,r0,r1
        CMP      r0,r5
        BHI      |L11.92|
|L11.144|
        NOP      
|L11.146|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L11.160|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r7
        B        |L11.22|
        ENDP

|L11.160|
        DCD      pFlash
|L11.164|
        DCD      0x0000c350
|L11.168|
        DCD      0x40022000

        AREA ||i.HAL_FLASHEx_Erase_IT||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_Erase_IT PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        NOP      
        LDR      r0,|L12.96|
        LDRB     r0,[r0,#0x18]  ; pFlash
        CMP      r0,#1
        BNE      |L12.20|
        MOVS     r0,#2
|L12.18|
        POP      {r4-r6,pc}
|L12.20|
        MOVS     r0,#1
        LDR      r1,|L12.96|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r1
        LDRB     r0,[r0,#0]  ; pFlash
        CMP      r0,#0
        BEQ      |L12.40|
        MOVS     r0,#1
        B        |L12.18|
|L12.40|
        LDR      r0,|L12.100|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#5
        LSLS     r1,r1,#10
        ORRS     r0,r0,r1
        LDR      r1,|L12.100|
        STR      r0,[r1,#0x10]
        LDR      r0,[r4,#0]
        CMP      r0,#1
        BNE      |L12.72|
        MOVS     r0,#2
        LDR      r1,|L12.96|
        STRB     r0,[r1,#0]
        BL       FLASH_MassErase
        B        |L12.92|
|L12.72|
        MOVS     r0,#1
        LDR      r1,|L12.96|
        STRB     r0,[r1,#0]
        LDR      r0,[r4,#8]
        STR      r0,[r1,#4]  ; pFlash
        LDR      r0,[r4,#4]
        STR      r0,[r1,#8]  ; pFlash
        LDR      r0,[r4,#4]
        BL       FLASH_PageErase
|L12.92|
        MOV      r0,r5
        B        |L12.18|
        ENDP

|L12.96|
        DCD      pFlash
|L12.100|
        DCD      0x40022000

        AREA ||i.HAL_FLASHEx_OBErase||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_OBErase PROC
        PUSH     {r4-r6,lr}
        MOVS     r5,#0xaa
        MOVS     r4,#1
        BL       FLASH_OB_GetRDP
        UXTB     r5,r0
        LDR      r0,|L13.88|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        CMP      r4,#0
        BNE      |L13.84|
        LDR      r1,|L13.92|
        STR      r0,[r1,#0x1c]  ; pFlash
        LDR      r0,|L13.96|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x20
        ORRS     r0,r0,r1
        LDR      r1,|L13.96|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x40
        ORRS     r0,r0,r1
        LDR      r1,|L13.96|
        STR      r0,[r1,#0x10]
        LDR      r0,|L13.88|
        BL       FLASH_WaitForLastOperation
        MOV      r4,r0
        LDR      r0,|L13.96|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#0x20
        BICS     r0,r0,r1
        LDR      r1,|L13.96|
        STR      r0,[r1,#0x10]
        CMP      r4,#0
        BNE      |L13.84|
        MOV      r0,r5
        BL       FLASH_OB_RDP_LevelConfig
        MOV      r4,r0
|L13.84|
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

|L13.88|
        DCD      0x0000c350
|L13.92|
        DCD      pFlash
|L13.96|
        DCD      0x40022000

        AREA ||i.HAL_FLASHEx_OBGetConfig||, CODE, READONLY, ALIGN=1

HAL_FLASHEx_OBGetConfig PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOVS     r0,#7
        STR      r0,[r4,#0]
        BL       FLASH_OB_GetWRP
        STR      r0,[r4,#8]
        BL       FLASH_OB_GetRDP
        STRB     r0,[r4,#0xc]
        BL       FLASH_OB_GetUser
        STRB     r0,[r4,#0xd]
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_FLASHEx_OBGetUserData||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_OBGetUserData PROC
        MOV      r1,r0
        MOVS     r0,#0
        LDR      r2,|L15.32|
        CMP      r1,r2
        BNE      |L15.24|
        LDR      r2,|L15.36|
        LDR      r2,[r2,#0x1c]
        MOVS     r3,#0xff
        LSLS     r3,r3,#16
        ANDS     r2,r2,r3
        LSRS     r0,r2,#16
        B        |L15.30|
|L15.24|
        LDR      r2,|L15.36|
        LDR      r2,[r2,#0x1c]
        LSRS     r0,r2,#24
|L15.30|
        BX       lr
        ENDP

|L15.32|
        DCD      0x1ffff804
|L15.36|
        DCD      0x40022000

        AREA ||i.HAL_FLASHEx_OBProgram||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_OBProgram PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#1
        NOP      
        LDR      r0,|L16.204|
        LDRB     r0,[r0,#0x18]  ; pFlash
        CMP      r0,#1
        BNE      |L16.20|
        MOVS     r0,#2
|L16.18|
        POP      {r4-r6,pc}
|L16.20|
        MOVS     r0,#1
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        LDRB     r0,[r4,#0]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        CMP      r0,#0
        BEQ      |L16.80|
        LDR      r0,[r4,#4]
        CMP      r0,#1
        BNE      |L16.54|
        LDR      r0,[r4,#8]
        BL       FLASH_OB_EnableWRP
        MOV      r5,r0
        B        |L16.62|
|L16.54|
        LDR      r0,[r4,#8]
        BL       FLASH_OB_DisableWRP
        MOV      r5,r0
|L16.62|
        CMP      r5,#0
        BEQ      |L16.80|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r5
        B        |L16.18|
|L16.80|
        MOVS     r1,#2
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,#2
        BNE      |L16.116|
        LDRB     r0,[r4,#0xc]
        BL       FLASH_OB_RDP_LevelConfig
        MOV      r5,r0
        CMP      r5,#0
        BEQ      |L16.116|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r5
        B        |L16.18|
|L16.116|
        MOVS     r1,#4
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,#4
        BNE      |L16.152|
        LDRB     r0,[r4,#0xd]
        BL       FLASH_OB_UserConfig
        MOV      r5,r0
        CMP      r5,#0
        BEQ      |L16.152|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r5
        B        |L16.18|
|L16.152|
        MOVS     r1,#8
        LDR      r0,[r4,#0]
        ANDS     r0,r0,r1
        CMP      r0,#8
        BNE      |L16.190|
        LDRB     r1,[r4,#0x14]
        LDR      r0,[r4,#0x10]
        BL       FLASH_OB_ProgramData
        MOV      r5,r0
        CMP      r5,#0
        BEQ      |L16.190|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r5
        B        |L16.18|
|L16.190|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L16.204|
        STRB     r0,[r1,#0x18]
        NOP      
        MOV      r0,r5
        B        |L16.18|
        ENDP

|L16.204|
        DCD      pFlash

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "C:\\Keil_v5\\ARM\\PACK\\Keil\\STM32F0xx_DFP\\2.0.0\\Drivers\\STM32F0xx_HAL_Driver\\Src\\stm32f0xx_hal_flash_ex.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___24_stm32f0xx_hal_flash_ex_c_6648b60e____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___24_stm32f0xx_hal_flash_ex_c_6648b60e____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___24_stm32f0xx_hal_flash_ex_c_6648b60e____REVSH|
#line 478
|__asm___24_stm32f0xx_hal_flash_ex_c_6648b60e____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT FLASH_PageErase [CODE]
        EXPORT HAL_FLASHEx_Erase [CODE]
        EXPORT HAL_FLASHEx_Erase_IT [CODE]
        EXPORT HAL_FLASHEx_OBErase [CODE]
        EXPORT HAL_FLASHEx_OBGetConfig [CODE]
        EXPORT HAL_FLASHEx_OBGetUserData [CODE]
        EXPORT HAL_FLASHEx_OBProgram [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT pFlash [DATA]
        IMPORT FLASH_WaitForLastOperation [CODE]

        KEEP FLASH_MassErase
        KEEP FLASH_OB_DisableWRP
        KEEP FLASH_OB_EnableWRP
        KEEP FLASH_OB_GetRDP
        KEEP FLASH_OB_GetUser
        KEEP FLASH_OB_GetWRP
        KEEP FLASH_OB_ProgramData
        KEEP FLASH_OB_RDP_LevelConfig
        KEEP FLASH_OB_UserConfig

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
