
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[XPAR_XAXIDMA_NUM_INSTANCES] =
{
	{
		XPAR_ADC_DMA_DEVICE_ID,
		XPAR_ADC_DMA_BASEADDR,
		XPAR_ADC_DMA_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_ADC_DMA_INCLUDE_MM2S,
		XPAR_ADC_DMA_INCLUDE_MM2S_DRE,
		XPAR_ADC_DMA_M_AXI_MM2S_DATA_WIDTH,
		XPAR_ADC_DMA_INCLUDE_S2MM,
		XPAR_ADC_DMA_INCLUDE_S2MM_DRE,
		XPAR_ADC_DMA_M_AXI_S2MM_DATA_WIDTH,
		XPAR_ADC_DMA_INCLUDE_SG,
		XPAR_ADC_DMA_NUM_MM2S_CHANNELS,
		XPAR_ADC_DMA_NUM_S2MM_CHANNELS,
		XPAR_ADC_DMA_MM2S_BURST_SIZE,
		XPAR_ADC_DMA_S2MM_BURST_SIZE,
		XPAR_ADC_DMA_MICRO_DMA,
		XPAR_ADC_DMA_ADDR_WIDTH,
		XPAR_ADC_DMA_SG_LENGTH_WIDTH
	},
	{
		XPAR_MIPI_DMA_DEVICE_ID,
		XPAR_MIPI_DMA_BASEADDR,
		XPAR_MIPI_DMA_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_MIPI_DMA_INCLUDE_MM2S,
		XPAR_MIPI_DMA_INCLUDE_MM2S_DRE,
		XPAR_MIPI_DMA_M_AXI_MM2S_DATA_WIDTH,
		XPAR_MIPI_DMA_INCLUDE_S2MM,
		XPAR_MIPI_DMA_INCLUDE_S2MM_DRE,
		XPAR_MIPI_DMA_M_AXI_S2MM_DATA_WIDTH,
		XPAR_MIPI_DMA_INCLUDE_SG,
		XPAR_MIPI_DMA_NUM_MM2S_CHANNELS,
		XPAR_MIPI_DMA_NUM_S2MM_CHANNELS,
		XPAR_MIPI_DMA_MM2S_BURST_SIZE,
		XPAR_MIPI_DMA_S2MM_BURST_SIZE,
		XPAR_MIPI_DMA_MICRO_DMA,
		XPAR_MIPI_DMA_ADDR_WIDTH,
		XPAR_MIPI_DMA_SG_LENGTH_WIDTH
	}
};


