webtalk_init -webtalk_dir C:\\Users\\Tom\\Documents\\Projects\\Scopy_MVP_Platform\\scopy-fpga\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-07-21 16:12:16" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211239692_0_0_466" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mvt9i6aqjkl0ojfnvtcv61l34s" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3800X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3893 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.665 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1584875893196" -context "vitis\\\\platform/1584875893196"
webtalk_add_data -client vitis -key platform_domain_count -value "2" -context "vitis\\\\platform/1584875893196"
webtalk_add_data -client vitis -key platform_linux_domain_count -value "0" -context "vitis\\\\platform/1584875893196"
webtalk_add_data -client vitis -key platform_baremetal_domain_count -value "2" -context "vitis\\\\platform/1584875893196"
webtalk_add_data -client vitis -key platform_linux_build_flow_count -value "0" -context "vitis\\\\platform/1584875893196"
webtalk_add_data -client vitis -key platform_custom_os_domain_count -value "0" -context "vitis\\\\platform/1584875893196"
webtalk_transmit -clientid 3216003749 -regid "211239692_0_0_466" -xml C:\\Users\\Tom\\Documents\\Projects\\Scopy_MVP_Platform\\scopy-fpga\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\Tom\\Documents\\Projects\\Scopy_MVP_Platform\\scopy-fpga\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\Tom\\Documents\\Projects\\Scopy_MVP_Platform\\scopy-fpga\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
